import { useEffect, useState } from 'react';
import { AlertTriangle, CheckCircle2, Clock3, RefreshCw, ShieldAlert, UserCheck } from 'lucide-react';
import type { EmployeeRecord } from '../../services/employeeApi';
import { CustomerPortalSessionExpiredError, getCompanyEmergencyRequests, updateCompanyEmergencyRequest, type EmergencyRequestRecord } from '../../services/customerPortalApi';

export default function OwnerEmergencyRequests({ accessToken, employees, onSessionExpired }: { accessToken: string; employees: EmployeeRecord[]; onSessionExpired: () => void }) {
  const [items, setItems] = useState<EmergencyRequestRecord[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState<string | null>(null); const [open, setOpen] = useState(true);
  const load = async () => { setLoading(true); setError(null); try { setItems(await getCompanyEmergencyRequests(accessToken)); } catch (loadError) { if (loadError instanceof CustomerPortalSessionExpiredError) return onSessionExpired(); setError(loadError instanceof Error ? loadError.message : 'Acil çağrılar yüklenemedi.'); } finally { setLoading(false); } };
  useEffect(() => { void load(); }, [accessToken]);
  const update = async (item: EmergencyRequestRecord, status: string, employeeAccountId = item.assignedEmployeeAccountId) => { try { const updated = await updateCompanyEmergencyRequest(accessToken, item.id, { status, employeeAccountId, note: status === 'Acknowledged' ? 'Firma sahibi talebi kabul etti.' : status === 'Planned' ? 'Talep saha planına alındı.' : 'Acil çağrı kapatıldı.' }); setItems((current) => current.map((value) => value.id === updated.id ? updated : value)); } catch (actionError) { if (actionError instanceof CustomerPortalSessionExpiredError) return onSessionExpired(); setError(actionError instanceof Error ? actionError.message : 'Talep güncellenemedi.'); } };
  const active = items.filter((item) => !['Completed', 'Cancelled'].includes(item.status));
  return <section className={`surface owner-emergency-panel ${active.length ? 'has-alerts' : ''}`}><button className="owner-emergency-heading" onClick={() => setOpen((value) => !value)}><span><ShieldAlert size={19} /></span><div><strong>Acil çağrı merkezi</strong><small>{active.length ? `${active.length} açık müşteri talebi işlem bekliyor` : 'Açık acil çağrı bulunmuyor'}</small></div><em>{active.length}</em></button>{open && <div className="owner-emergency-content">{error && <div className="field-operation-error"><AlertTriangle size={15} />{error}<button onClick={() => void load()}><RefreshCw size={14} /> Yenile</button></div>}{loading ? <div className="owner-emergency-loading"><RefreshCw className="spin-icon" size={19} /> Talepler yükleniyor…</div> : active.length === 0 ? <div className="owner-emergency-empty"><CheckCircle2 size={18} /> Tüm müşteri çağrıları sonuçlandırılmış durumda.</div> : active.map((item) => <article key={item.id} className={`owner-emergency-row priority-${item.priority.toLowerCase()}`}><div className="owner-emergency-id"><strong>{item.number}</strong><span>{item.customerName} · {item.branchName}</span><small><Clock3 size={12} />{formatDate(item.requestedAt)} · {priorityLabel(item.priority)}</small></div><p>{item.description}</p><label><UserCheck size={14} /><select value={item.assignedEmployeeAccountId ?? ''} onChange={(event) => void update(item, item.status === 'New' ? 'Acknowledged' : item.status, event.target.value || undefined)}><option value="">Personel ata</option>{employees.filter((employee) => employee.isActive).map((employee) => <option value={employee.id} key={employee.id}>{employee.name}</option>)}</select></label><div className="owner-emergency-actions">{item.status === 'New' && <button onClick={() => void update(item, 'Acknowledged')}>Kabul et</button>}{item.status === 'Acknowledged' && <button onClick={() => void update(item, 'Planned')}>Planlandı</button>}<button className="complete" onClick={() => void update(item, 'Completed')}><CheckCircle2 size={14} /> Tamamla</button></div></article>)}</div>}</section>;
}
function formatDate(value: string) { return new Intl.DateTimeFormat('tr-TR', { day: '2-digit', month: 'short', hour: '2-digit', minute: '2-digit' }).format(new Date(value)); }
function priorityLabel(value: string) { return ({ Normal: 'Normal', Urgent: 'Acil', Critical: 'Kritik' } as Record<string,string>)[value] ?? value; }
