import { useEffect, useMemo, useRef, useState, type FormEvent } from 'react';
import { AlertTriangle, Building2, CalendarDays, CheckCircle2, Clock3, FileCheck2, FileText, MapPin, Plus, Printer, RefreshCw, ShieldAlert, Store, X } from 'lucide-react';
import { useReactToPrint } from 'react-to-print';
import type { AuthenticatedSession } from '../auth/types';
import ServiceReportPrintSheet from '../components/report/ServiceReportPrintSheet';
import { getCustomerServiceReports, type ServiceReportRecord } from '../services/serviceReportApi';
import { createEmergencyRequest, CustomerPortalSessionExpiredError, getCustomerPortalSummary, type CreateEmergencyRequestInput, type CustomerPortalSummary } from '../services/customerPortalApi';
import PortalHeader from './PortalHeader';

type Tab = 'overview' | 'services' | 'reports' | 'requests';

export default function CustomerPortal({ session, onLogout }: { session: AuthenticatedSession; onLogout: () => void }) {
  const [summary, setSummary] = useState<CustomerPortalSummary | null>(null); const [reports, setReports] = useState<ServiceReportRecord[]>([]);
  const [tab, setTab] = useState<Tab>('overview'); const [loading, setLoading] = useState(true); const [error, setError] = useState<string | null>(null);
  const [requestOpen, setRequestOpen] = useState(false); const [preview, setPreview] = useState<ServiceReportRecord | null>(null);
  const printRef = useRef<HTMLDivElement>(null); const print = useReactToPrint({ contentRef: printRef, documentTitle: preview ? `${preview.reportNumber}_${preview.branchName}` : 'Pestneer_Hizmet_Raporu' });
  const load = async () => { setLoading(true); setError(null); try { const [portal, reportItems] = await Promise.all([getCustomerPortalSummary(session.accessToken), getCustomerServiceReports(session.accessToken)]); setSummary(portal); setReports(reportItems); } catch (loadError) { if (loadError instanceof CustomerPortalSessionExpiredError) return onLogout(); setError(loadError instanceof Error ? loadError.message : 'Müşteri verileri yüklenemedi.'); } finally { setLoading(false); } };
  useEffect(() => { void load(); }, [session.accessToken]);
  const openRequests = summary?.emergencyRequests.filter((item) => !['Completed', 'Cancelled'].includes(item.status)).length ?? 0;
  const allServices = useMemo(() => [...(summary?.upcomingWorkOrders ?? []), ...(summary?.completedWorkOrders ?? [])].sort((a, b) => b.scheduledAt.localeCompare(a.scheduledAt)), [summary]);
  const submitRequest = async (input: CreateEmergencyRequestInput) => { const created = await createEmergencyRequest(session.accessToken, input); setSummary((current) => current ? { ...current, emergencyRequests: [created, ...current.emergencyRequests] } : current); setRequestOpen(false); setTab('requests'); };

  return <div className="role-portal customer-portal"><PortalHeader session={session} onLogout={onLogout} context="MÜŞTERİ PORTALI" />
    <main className="role-portal-main customer-portal-main">
      <div className="role-welcome"><div><p>MÜŞTERİ OPERASYONLARI</p><h1>{summary?.customerName ?? 'Hizmetleriniz tek ekranda'}</h1><span>{summary?.scope === 'Branch' ? 'Yalnızca yetkili olduğunuz şubenin hizmetleri gösteriliyor.' : 'Şubelerinizi, uygulama raporlarını ve yaklaşan kontrolleri güvenle takip edin.'}</span></div><button onClick={() => setRequestOpen(true)}><ShieldAlert size={18} />Acil çağrı oluştur</button></div>
      <nav className="customer-portal-tabs">{([['overview','Genel Bakış'],['services','Hizmetler'],['reports','Raporlar'],['requests',`Acil Çağrılar${openRequests ? ` (${openRequests})` : ''}`]] as [Tab,string][]).map(([value,label]) => <button key={value} className={tab === value ? 'active' : ''} onClick={() => setTab(value)}>{label}</button>)}<button className="customer-refresh" onClick={() => void load()} aria-label="Yenile"><RefreshCw size={16} /></button></nav>
      {loading ? <PortalState icon={<RefreshCw className="spin-icon" />} text="Müşteri portalı hazırlanıyor…" /> : error || !summary ? <PortalState icon={<AlertTriangle />} text={error ?? 'Müşteri kaydı bulunamadı.'} action={() => void load()} /> : <>
        {tab === 'overview' && <><div className="customer-kpis"><Kpi label="Yetkili şube" value={summary.branches.length} detail={summary.scope === 'Branch' ? 'Şube kapsamlı hesap' : 'Çatı müşteri hesabı'} icon={<Building2 />} /><Kpi label="Yaklaşan hizmet" value={summary.upcomingWorkOrders.length} detail="Planlanan ve sahadaki" icon={<CalendarDays />} /><Kpi label="İmzalı rapor" value={reports.length} detail="Yayınlanan hizmet raporu" icon={<FileCheck2 />} /><Kpi label="Açık çağrı" value={openRequests} detail="Takip edilen talep" icon={<ShieldAlert />} /></div>
          <div className="customer-layout"><section className="role-surface upcoming-service"><div className="role-section-title"><div><p>YAKLAŞAN HİZMET</p><h2>Bir sonraki uygulama</h2></div></div>{summary.upcomingWorkOrders[0] ? <ServiceCard item={summary.upcomingWorkOrders[0]} /> : <Empty icon={<CalendarDays />} text="Planlanmış yaklaşan hizmet bulunmuyor." />}</section>
          <section className="role-surface recent-documents"><div className="role-section-title"><div><p>BELGELER</p><h2>Son hizmet raporları</h2></div><button onClick={() => setTab('reports')}>Tüm raporlar</button></div>{reports.slice(0, 3).map((report) => <button className="document-row customer-document-button" key={report.id} onClick={() => setPreview(report)}><span><FileText size={18} /></span><div><strong>{report.branchName}</strong><small>{formatDate(report.scheduledAt)} · {report.reportNumber}</small></div><Printer size={17} /></button>)}{reports.length === 0 && <Empty icon={<FileText />} text="Henüz yayınlanmış rapor yok." />}</section></div></>}
        {tab === 'services' && <section className="role-surface customer-list-surface"><div className="role-section-title"><div><p>HİZMET GEÇMİŞİ</p><h2>Planlanan ve tamamlanan işler</h2></div></div><div className="customer-service-list">{allServices.map((item) => <ServiceCard key={item.id} item={item} />)}{allServices.length === 0 && <Empty icon={<CalendarDays />} text="Hizmet kaydı bulunmuyor." />}</div></section>}
        {tab === 'reports' && <section className="role-surface customer-list-surface"><div className="role-section-title"><div><p>RESMİ BELGELER</p><h2>İmzalı hizmet raporları</h2></div></div><div className="customer-report-grid">{reports.map((report) => <article key={report.id}><span><FileCheck2 /></span><div><strong>{report.reportNumber}</strong><small>{report.branchName} · {formatDate(report.scheduledAt)}</small><em>{report.totalStations} istasyon · %{report.activityRate} aktivite</em></div><button onClick={() => setPreview(report)}><Printer size={15} /> Görüntüle</button></article>)}{reports.length === 0 && <Empty icon={<FileText />} text="Henüz yayınlanmış rapor yok." />}</div></section>}
        {tab === 'requests' && <section className="role-surface customer-list-surface"><div className="role-section-title"><div><p>ACİL ÇAĞRI MERKEZİ</p><h2>Talepler ve yanıt geçmişi</h2></div><button className="role-primary-button" onClick={() => setRequestOpen(true)}><Plus size={16} /> Yeni talep</button></div><div className="emergency-request-list">{summary.emergencyRequests.map((item) => <article key={item.id} className={`priority-${item.priority.toLowerCase()}`}><div><span>{item.number}</span><strong>{item.branchName}</strong><small>{formatDateTime(item.requestedAt)} · {priorityLabel(item.priority)}</small></div><p>{item.description}</p><div><em>{statusLabel(item.status)}</em><span>Atanan: {item.employeeName}</span>{item.acknowledgedAt && <span>Yanıt: {formatDuration(item.requestedAt, item.acknowledgedAt)}</span>}</div></article>)}{summary.emergencyRequests.length === 0 && <Empty icon={<ShieldAlert />} text="Acil çağrı talebi bulunmuyor." />}</div></section>}
      </>}
    </main>
    {requestOpen && summary && <EmergencyRequestModal summary={summary} onClose={() => setRequestOpen(false)} onSubmit={submitRequest} />}
    {preview && <div className="modal-layer report-preview-layer"><div className="report-preview-dialog"><div className="report-preview-toolbar"><div><strong>{preview.reportNumber}</strong><span>{preview.customerName} · {preview.branchName}</span></div><button onClick={print}><Printer size={16} /> PDF / Yazdır</button><button className="icon-button" onClick={() => setPreview(null)}><X size={19} /></button></div><div className="report-print-canvas"><div ref={printRef}><ServiceReportPrintSheet report={preview} accessToken={session.accessToken} /></div></div></div></div>}
  </div>;
}

function EmergencyRequestModal({ summary, onClose, onSubmit }: { summary: CustomerPortalSummary; onClose: () => void; onSubmit: (input: CreateEmergencyRequestInput) => Promise<void> }) {
  const [saving, setSaving] = useState(false); const [error, setError] = useState<string | null>(null);
  const submit = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const data = new FormData(event.currentTarget); setSaving(true); setError(null); try { await onSubmit({ branchId: String(data.get('branchId') || '') || undefined, serviceType: String(data.get('serviceType')) as CreateEmergencyRequestInput['serviceType'], priority: String(data.get('priority')) as CreateEmergencyRequestInput['priority'], contactPhone: String(data.get('contactPhone') || '') || undefined, description: String(data.get('description')) }); } catch (submitError) { setError(submitError instanceof Error ? submitError.message : 'Talep oluşturulamadı.'); } finally { setSaving(false); } };
  return <div className="modal-layer"><div className="modal emergency-request-modal"><div className="modal-header"><div><p className="eyebrow">ACİL ÇAĞRI</p><h2>Yeni hizmet talebi</h2><p>Talep firma sahibine ve şubenizden sorumlu personele anında iletilir.</p></div><button className="icon-button" onClick={onClose}><X /></button></div><form onSubmit={submit}><div className="form-grid"><label>Şube<select name="branchId" required={summary.branches.length > 0}><option value="">Merkez / Genel</option>{summary.branches.map((branch) => <option value={branch.id} key={branch.id}>{branch.name}</option>)}</select></label><label>Çağrı türü<select name="serviceType"><option value="EmergencyPaid">Ücretli acil çağrı</option><option value="EmergencyFree">Ücretsiz acil çağrı</option></select></label><label>Öncelik<select name="priority"><option value="Urgent">Acil</option><option value="Critical">Kritik</option><option value="Normal">Normal</option></select></label><label>İletişim telefonu<input name="contactPhone" type="tel" placeholder="05xx xxx xx xx" /></label><label className="form-field-wide">Sorun ve gözlemler<textarea name="description" required minLength={10} maxLength={2000} rows={5} placeholder="Zararlı görülen alanı, yoğunluğu ve erişim bilgilerini açıklayın." /></label></div>{error && <div className="modal-form-error">{error}</div>}<div className="modal-actions"><button type="button" className="secondary-button" onClick={onClose}>Vazgeç</button><button className="primary-button" disabled={saving}><ShieldAlert size={16} /> {saving ? 'Gönderiliyor…' : 'Acil Çağrıyı Gönder'}</button></div></form></div></div>;
}

function ServiceCard({ item }: { item: CustomerPortalSummary['upcomingWorkOrders'][number] }) { return <article className="customer-service-card"><span className={`service-status status-${item.status.toLowerCase()}`}>{statusLabel(item.status)}</span><div><strong>{item.branchName}</strong><small>{item.serviceType} · {item.employeeName}</small></div><div className="service-meta"><span><Clock3 size={15} />{formatDateTime(item.scheduledAt)} · {item.durationMinutes} dk.</span></div>{item.completionNote && <p><CheckCircle2 size={15} />{item.completionNote}</p>}</article>; }
function Kpi({ label, value, detail, icon }: { label: string; value: number; detail: string; icon: React.ReactNode }) { return <article><div><span>{label}</span><strong>{value}</strong><small>{detail}</small></div>{icon}</article>; }
function Empty({ icon, text }: { icon: React.ReactNode; text: string }) { return <div className="customer-empty">{icon}<span>{text}</span></div>; }
function PortalState({ icon, text, action }: { icon: React.ReactNode; text: string; action?: () => void }) { return <div className="role-surface customer-portal-state">{icon}<strong>{text}</strong>{action && <button onClick={action}>Tekrar dene</button>}</div>; }
function formatDate(value: string) { return new Intl.DateTimeFormat('tr-TR', { day: '2-digit', month: 'long', year: 'numeric' }).format(new Date(value)); }
function formatDateTime(value: string) { return new Intl.DateTimeFormat('tr-TR', { day: '2-digit', month: 'short', hour: '2-digit', minute: '2-digit' }).format(new Date(value)); }
function formatDuration(start: string, end: string) { const minutes = Math.max(0, Math.round((new Date(end).getTime() - new Date(start).getTime()) / 60000)); return minutes < 60 ? `${minutes} dk.` : `${Math.floor(minutes / 60)} sa. ${minutes % 60} dk.`; }
function statusLabel(value: string) { return ({ New: 'Yeni', Acknowledged: 'Kabul edildi', Planned: 'Planlandı', Completed: 'Tamamlandı', Cancelled: 'İptal', InProgress: 'Sahada' } as Record<string,string>)[value] ?? value; }
function priorityLabel(value: string) { return ({ Normal: 'Normal', Urgent: 'Acil', Critical: 'Kritik' } as Record<string,string>)[value] ?? value; }
