import { useEffect, useState } from 'react';
import { AlertCircle, CalendarPlus, CheckCircle2, Clock3, MapPin, Play, RefreshCw, Sparkles } from 'lucide-react';
import type { WorkOrder } from '../types';
import WorkOrderModal from '../components/modals/WorkOrderModal';
import WorkOrderCompletionModal from '../components/modals/WorkOrderCompletionModal';
import { completeEmployeeWorkOrder, getEmployeePlanningOptions, getEmployeeWorkOrders, selfScheduleWorkOrders, startEmployeeWorkOrder, WorkOrderSessionExpiredError, type CreateWorkOrdersInput, type EmployeePlanningOptions } from '../services/workOrderApi';

export default function EmployeeWorkOrdersPanel({ accessToken, onSessionExpired }: { accessToken: string; onSessionExpired: () => void }) {
  const [orders, setOrders] = useState<WorkOrder[]>([]); const [options, setOptions] = useState<EmployeePlanningOptions>({ canSelfSchedule: false, customers: [] }); const [loading, setLoading] = useState(true); const [error, setError] = useState<string | null>(null); const [selfModal, setSelfModal] = useState(false); const [completing, setCompleting] = useState<WorkOrder | null>(null);
  const load = async () => { setLoading(true); setError(null); try { const [items, planning] = await Promise.all([getEmployeeWorkOrders(accessToken), getEmployeePlanningOptions(accessToken)]); setOrders(items); setOptions(planning); } catch (loadError) { if (loadError instanceof WorkOrderSessionExpiredError) return onSessionExpired(); setError(loadError instanceof Error ? loadError.message : 'İş emirleri yüklenemedi.'); } finally { setLoading(false); } };
  useEffect(() => { void load(); }, [accessToken]);
  const replace = (updated: WorkOrder) => setOrders((current) => current.map((item) => item.recordId === updated.recordId ? updated : item));
  const start = async (order: WorkOrder) => { try { replace(await startEmployeeWorkOrder(accessToken, order.recordId)); } catch (actionError) { if (actionError instanceof WorkOrderSessionExpiredError) return onSessionExpired(); setError(actionError instanceof Error ? actionError.message : 'İş başlatılamadı.'); } };
  const complete = async (note: string, recommendation: string, photos: File[]) => { if (!completing) return; replace(await completeEmployeeWorkOrder(accessToken, completing.recordId, note, recommendation, photos)); setCompleting(null); };
  const selfSchedule = async (input: CreateWorkOrdersInput) => { const created = await selfScheduleWorkOrders(accessToken, input); setOrders((current) => [...current, ...created].sort((a, b) => a.scheduledAt.localeCompare(b.scheduledAt))); setSelfModal(false); };
  return <section className="role-surface employee-work-orders-page"><div className="role-section-title"><div><p>SAHA PROGRAMI</p><h2>İş Emirlerim</h2></div><div className="employee-work-actions">{options.canSelfSchedule && <button onClick={() => setSelfModal(true)}><CalendarPlus size={16} /> Kendime İş Planla</button>}<button className="icon-button" onClick={() => void load()}><RefreshCw size={16} /></button></div></div>{options.canSelfSchedule && <div className="self-schedule-permission"><Sparkles size={17} /><span>Firma sahibi, kendi iş programınızı oluşturma yetkisini etkinleştirdi.</span></div>}{error && <div className="field-operation-error"><AlertCircle size={16} /><span>{error}</span></div>}{loading ? <div className="field-loading"><RefreshCw className="spin-icon" size={26} /><span>İş emirleri yükleniyor…</span></div> : orders.length === 0 ? <div className="field-empty-work"><CalendarPlus size={24} /><div><strong>Atanmış iş emri bulunmuyor</strong><span>Yeni bir iş atandığında müşteri, şube, konum ve zaman bilgileri burada görünür.</span></div></div> : <div className="employee-work-list">{orders.map((order) => <article key={order.recordId} className={`employee-work-card work-${order.technicalStatus.toLowerCase()}`}><div className="employee-work-card-top"><div><span>{order.id}</span><strong>{order.client}</strong><small>{order.branch}</small></div><em>{order.status}</em></div><div className="employee-work-meta"><span><Clock3 size={15} />{order.date} · {order.time}</span><a href={order.branchMapUrl || `https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(order.branchAddress)}`} target="_blank" rel="noreferrer"><MapPin size={15} />{order.branchAddress}</a></div><div className="employee-work-service"><strong>{order.service}</strong><span>{visitLabel(order.visitType)}</span></div>{order.notes && <p>{order.notes}</p>}{order.completionNote && <div className="employee-completion-note"><CheckCircle2 size={16} /><span>{order.completionNote}</span></div>}<div className="employee-work-card-actions">{order.technicalStatus === 'Planned' && <button className="role-primary-button" onClick={() => void start(order)}><Play size={16} /> İlaçlamayı Başlat</button>}{order.technicalStatus === 'InProgress' && <button className="role-primary-button" onClick={() => setCompleting(order)}><CheckCircle2 size={16} /> İşlemi Bitir ve Raporla</button>}{order.technicalStatus === 'Completed' && <span className="work-completed-label"><CheckCircle2 size={16} /> Tamamlandı</span>}</div></article>)}</div>}{selfModal && <WorkOrderModal customers={options.customers} selfSchedule onClose={() => setSelfModal(false)} onCreate={selfSchedule} />}{completing && <WorkOrderCompletionModal order={completing} onClose={() => setCompleting(null)} onSubmit={complete} />}</section>;
}
function visitLabel(value: string) { return ({ Routine: 'Rutin hizmet', Extra: 'Ekstra hizmet', EmergencyPaid: 'Ücretli acil çağrı', EmergencyFree: 'Ücretsiz acil çağrı' } as Record<string, string>)[value] ?? value; }
