import { useEffect, useMemo, useState } from 'react';
import { AlertCircle, CalendarPlus, CheckCircle2, Clock3, FileCheck2, FilePlus2, MapPin, Play, RefreshCw, Sparkles } from 'lucide-react';
import type { WorkOrder } from '../types';
import WorkOrderModal from '../components/modals/WorkOrderModal';
import WorkOrderCompletionModal from '../components/modals/WorkOrderCompletionModal';
import ServiceReportModal from '../components/modals/ServiceReportModal';
import { completeEmployeeWorkOrder, getEmployeePlanningOptions, getEmployeeWorkOrders, selfScheduleWorkOrders, startEmployeeWorkOrder, WorkOrderSessionExpiredError, type CreateWorkOrdersInput, type EmployeePlanningOptions } from '../services/workOrderApi';
import { getEmployeeServiceReports, ReportSessionExpiredError, saveServiceReport, type ServiceReportRecord, type UpsertServiceReportInput } from '../services/serviceReportApi';

type Props = { accessToken: string; companyName: string; operatorName: string; onSessionExpired: () => void };

export default function EmployeeWorkOrdersPanel({ accessToken, companyName, operatorName, onSessionExpired }: Props) {
  const [orders, setOrders] = useState<WorkOrder[]>([]); const [reports, setReports] = useState<ServiceReportRecord[]>([]); const [options, setOptions] = useState<EmployeePlanningOptions>({ canSelfSchedule: false, customers: [] });
  const [loading, setLoading] = useState(true); const [error, setError] = useState<string | null>(null); const [selfModal, setSelfModal] = useState(false); const [completing, setCompleting] = useState<WorkOrder | null>(null); const [reporting, setReporting] = useState<WorkOrder | null>(null);
  const reportByOrder = useMemo(() => new Map(reports.map((item) => [item.workOrderId, item])), [reports]);

  const load = async () => { setLoading(true); setError(null); try { const [items, planning, reportItems] = await Promise.all([getEmployeeWorkOrders(accessToken), getEmployeePlanningOptions(accessToken), getEmployeeServiceReports(accessToken)]); setOrders(items); setOptions(planning); setReports(reportItems); } catch (loadError) { if (loadError instanceof WorkOrderSessionExpiredError || loadError instanceof ReportSessionExpiredError) return onSessionExpired(); setError(loadError instanceof Error ? loadError.message : 'İş emirleri yüklenemedi.'); } finally { setLoading(false); } };
  useEffect(() => { void load(); }, [accessToken]);
  const replace = (updated: WorkOrder) => setOrders((current) => current.map((item) => item.recordId === updated.recordId ? updated : item));
  const start = async (order: WorkOrder) => { try { replace(await startEmployeeWorkOrder(accessToken, order.recordId)); } catch (actionError) { if (actionError instanceof WorkOrderSessionExpiredError) return onSessionExpired(); setError(actionError instanceof Error ? actionError.message : 'İş başlatılamadı.'); } };
  const complete = async (note: string, recommendation: string, photos: File[]) => { if (!completing) return; replace(await completeEmployeeWorkOrder(accessToken, completing.recordId, note, recommendation, photos)); setCompleting(null); };
  const selfSchedule = async (input: CreateWorkOrdersInput) => { const created = await selfScheduleWorkOrders(accessToken, input); setOrders((current) => [...current, ...created].sort((a, b) => a.scheduledAt.localeCompare(b.scheduledAt))); setSelfModal(false); };
  const saveReport = async (input: UpsertServiceReportInput) => { if (!reporting) return; const saved = await saveServiceReport(accessToken, reporting.recordId, input); setReports((current) => [saved, ...current.filter((item) => item.id !== saved.id)]); setReporting(null); };

  return <section className="role-surface employee-work-orders-page"><div className="role-section-title"><div><p>SAHA PROGRAMI</p><h2>İş Emirlerim</h2></div><div className="employee-work-actions">{options.canSelfSchedule && <button onClick={() => setSelfModal(true)}><CalendarPlus size={16} /> Kendime İş Planla</button>}<button className="icon-button" onClick={() => void load()}><RefreshCw size={16} /></button></div></div>
    {options.canSelfSchedule && <div className="self-schedule-permission"><Sparkles size={17} /><span>Firma sahibi, kendi iş programınızı oluşturma yetkisini etkinleştirdi.</span></div>}{error && <div className="field-operation-error"><AlertCircle size={16} /><span>{error}</span></div>}
    {loading ? <div className="field-loading"><RefreshCw className="spin-icon" size={26} /><span>İş emirleri yükleniyor…</span></div> : orders.length === 0 ? <div className="field-empty-work"><CalendarPlus size={24} /><div><strong>Atanmış iş emri bulunmuyor</strong><span>Yeni bir iş atandığında müşteri, şube, konum ve zaman bilgileri burada görünür.</span></div></div> : <div className="employee-work-list">{orders.map((order) => { const report = reportByOrder.get(order.recordId); return <article key={order.recordId} className={`employee-work-card work-${order.technicalStatus.toLowerCase()}`}><div className="employee-work-card-top"><div><span>{order.id}</span><strong>{order.client}</strong><small>{order.branch}</small></div><em>{order.status}</em></div><div className="employee-work-meta"><span><Clock3 size={15} />{order.date} · {order.time}</span><a href={order.branchMapUrl || `https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(order.branchAddress)}`} target="_blank" rel="noreferrer"><MapPin size={15} />{order.branchAddress}</a></div><div className="employee-work-service"><strong>{order.service}</strong><span>{visitLabel(order.visitType)}</span></div>{order.notes && <p>{order.notes}</p>}{order.completionNote && <div className="employee-completion-note"><CheckCircle2 size={16} /><span>{order.completionNote}</span></div>}
      {report && <div className={`employee-report-state ${report.status.toLowerCase()}`}><FileCheck2 size={16} /><span>{report.status === 'Finalized' ? `Rapor onaylandı · ${report.totalStations} istasyon · ${riskLabel(report.riskLevel)} risk` : 'Saha raporu taslak olarak kaydedildi'}</span></div>}
      <div className="employee-work-card-actions">{order.technicalStatus === 'Planned' && <button className="role-primary-button" onClick={() => void start(order)}><Play size={16} /> İlaçlamayı Başlat</button>}{order.technicalStatus === 'InProgress' && <><button className="role-primary-button" onClick={() => setCompleting(order)}><CheckCircle2 size={16} /> İşlemi Bitir</button><button className="employee-report-button" onClick={() => setReporting(order)}><FilePlus2 size={16} /> {report ? 'Raporu aç' : 'Saha raporu'}</button></>}{order.technicalStatus === 'Completed' && <><span className="work-completed-label"><CheckCircle2 size={16} /> Tamamlandı</span><button className="employee-report-button" onClick={() => setReporting(order)}><FileCheck2 size={16} /> {report ? 'Raporu görüntüle' : 'Rapor oluştur'}</button></>}</div></article>; })}</div>}
    {selfModal && <WorkOrderModal customers={options.customers} selfSchedule onClose={() => setSelfModal(false)} onCreate={selfSchedule} />}{completing && <WorkOrderCompletionModal order={completing} onClose={() => setCompleting(null)} onSubmit={complete} />}
    {reporting && <ServiceReportModal order={reporting} existing={reportByOrder.get(reporting.recordId)} companyName={companyName} operatorName={operatorName} readOnly={reportByOrder.get(reporting.recordId)?.status === 'Finalized'} onClose={() => setReporting(null)} onSave={saveReport} />}
  </section>;
}
function visitLabel(value: string) { return ({ Routine: 'Rutin hizmet', Extra: 'Ekstra hizmet', EmergencyPaid: 'Ücretli acil çağrı', EmergencyFree: 'Ücretsiz acil çağrı' } as Record<string, string>)[value] ?? value; }
function riskLabel(value: string) { return ({ Low: 'Düşük', Medium: 'Orta', High: 'Yüksek' } as Record<string, string>)[value] ?? value; }
