import { useEffect, useMemo, useState, type FormEvent } from 'react';
import { AlertTriangle, Archive, CheckCircle2, ChevronDown, Download, FileUp, Gauge, History, Leaf, Plus, Share2, ShieldCheck, Trash2, X } from 'lucide-react';
import { createWasteDisposal, downloadWasteEvidence, getCompanyHealthScores, getCustomerHealthScores, getWasteDisposals, HealthWasteSessionExpiredError, shareWasteEvidence, updateWasteDisposal, uploadWasteEvidence, type HealthScoreLocation, type HealthScoreOverview, type WasteDisposalInput, type WasteDisposalRecord } from '../../services/healthWasteApi';

type Mode = 'staff' | 'customer';

export default function HealthWasteCenter({ accessToken, mode, onSessionExpired }: { accessToken: string; mode: Mode; onSessionExpired: () => void }) {
  const [health, setHealth] = useState<HealthScoreOverview | null>(null);
  const [waste, setWaste] = useState<WasteDisposalRecord[]>([]);
  const [loading, setLoading] = useState(true); const [error, setError] = useState<string | null>(null); const [modalOpen, setModalOpen] = useState(false);
  const load = async () => { setLoading(true); setError(null); try { const overview = await (mode === 'customer' ? getCustomerHealthScores(accessToken) : getCompanyHealthScores(accessToken)); setHealth(overview); if (mode === 'staff') setWaste(await getWasteDisposals(accessToken)); } catch (loadError) { if (loadError instanceof HealthWasteSessionExpiredError) return onSessionExpired(); setError(loadError instanceof Error ? loadError.message : 'Sağlık verileri yüklenemedi.'); } finally { setLoading(false); } };
  useEffect(() => { void load(); }, [accessToken, mode]);
  const highRisk = health?.locations.filter((item) => item.level === 'High').length ?? 0;
  const disposed = waste.filter((item) => item.status === 'Disposed').length;

  if (loading) return <div className="health-state"><History className="spin-icon" /><strong>Şube sağlık verileri hazırlanıyor…</strong></div>;
  if (error || !health) return <div className="health-state error"><AlertTriangle /><strong>{error ?? 'Sağlık skoru oluşturulamadı.'}</strong><button className="btn btn-outline" onClick={() => void load()}>Tekrar dene</button></div>;

  return <div className={`health-waste-center ${mode}`}>
    <div className="health-center-heading"><div><p className="eyebrow">AÇIKLANABİLİR ŞUBE SAĞLIĞI</p><h2>Müşteri Sağlık Skoru</h2><span>Puan yalnızca mevcut saha verilerinden hesaplanır; veri bulunmayan başlıklar sonucu düşürmez.</span></div>{mode === 'staff' && <button className="btn btn-primary" onClick={() => setModalOpen(true)}><Plus size={17} />Opsiyonel bertaraf kaydı</button>}</div>
    <div className="health-kpis"><article><span className="blue"><Gauge /></span><div><small>Ortalama sağlık</small><strong>{health.averageScore}/100</strong></div></article><article><span className="red"><AlertTriangle /></span><div><small>Yüksek risk</small><strong>{highRisk}</strong></div></article><article><span className="purple"><History /></span><div><small>Dönem karşılaştırması</small><strong>{health.comparisonAvailableLocations}</strong></div></article>{mode === 'staff' && <article><span className="green"><Leaf /></span><div><small>Opsiyonel bertaraf</small><strong>{disposed}/{waste.length}</strong></div></article>}</div>
    <div className="health-location-grid">{health.locations.map((item) => <HealthLocationCard key={`${item.customerId}-${item.branchId ?? 'center'}`} item={item} />)}{health.locations.length === 0 && <div className="health-state"><ShieldCheck /><strong>Sağlık skoru üretilecek aktif lokasyon bulunmuyor.</strong></div>}</div>
    {mode === 'staff' && <section className="optional-waste-section"><div className="optional-waste-heading"><div><p className="eyebrow">OPSİYONEL KAYIT</p><h2>Atık ve bertaraf izleme</h2><span>Bu kayıt iş emri ve rapor tamamlamanın şartı değildir. İhtiyaç halinde izlenebilirlik kanıtı oluşturur.</span></div><b>Zorunlu değil</b></div><div className="waste-grid">{waste.map((item) => <WasteCard key={item.id} item={item} token={accessToken} onChanged={(updated) => setWaste((current) => current.map((record) => record.id === updated.id ? updated : record))} onSessionExpired={onSessionExpired} />)}{waste.length === 0 && <div className="health-state compact"><Trash2 /><strong>Henüz opsiyonel bertaraf kaydı oluşturulmadı.</strong></div>}</div></section>}
    {modalOpen && <WasteModal locations={health.locations} onClose={() => setModalOpen(false)} onSave={async (input) => { const created = await createWasteDisposal(accessToken, input); setWaste((current) => [created, ...current]); setModalOpen(false); }} />}
  </div>;
}

function HealthLocationCard({ item }: { item: HealthScoreLocation }) {
  const [expanded, setExpanded] = useState(false);
  const comparison = item.periodComparisonAvailable && item.activityRateChange !== undefined ? item.activityRateChange > 0 ? `Aktivite ${item.activityRateChange.toFixed(1)} puan arttı` : item.activityRateChange < 0 ? `Aktivite ${Math.abs(item.activityRateChange).toFixed(1)} puan azaldı` : 'Aktivite değişmedi' : 'Dönem karşılaştırması için veri birikiyor';
  return <article className={`health-location-card level-${item.level.toLowerCase()}`}><header><div><span>{item.customerName}</span><h3>{item.branchName}</h3><small>{item.address}</small></div><div className="health-score"><strong>{item.score}</strong><small>/100</small></div></header><div className="health-summary"><span>{healthLevel(item.level)}</span><span>Güven: {confidenceLabel(item.confidence)}</span><span>{item.currentReportCount} rapor</span></div><div className={`period-comparison ${item.periodComparisonAvailable ? 'available' : ''}`}><History size={15} /><span>{comparison}</span></div><button className="health-detail-toggle" onClick={() => setExpanded((value) => !value)}>Puanın nasıl hesaplandığını {expanded ? 'gizle' : 'göster'}<ChevronDown className={expanded ? 'open' : ''} /></button>{expanded && <div className="health-components">{item.components.map((component) => <div key={component.code} className={!component.available ? 'unavailable' : ''}><span><strong>{component.label}</strong><small>{component.detail}</small></span><b>{component.available ? `-${component.penalty}/${component.maxPenalty}` : 'Hariç'}</b></div>)}</div>}</article>;
}

function WasteCard({ item, token, onChanged, onSessionExpired }: { item: WasteDisposalRecord; token: string; onChanged: (item: WasteDisposalRecord) => void; onSessionExpired: () => void }) {
  const [busy, setBusy] = useState(false); const [error, setError] = useState<string | null>(null);
  const markDisposed = async () => { setBusy(true); setError(null); try { onChanged(await updateWasteDisposal(token, item.id, { wasteType: item.wasteType, quantity: item.quantity, unit: item.unit, status: 'Disposed', generatedAt: item.generatedAt, temporaryStorage: item.temporaryStorage, recipientName: item.recipientName, carrierOrFacility: item.carrierOrFacility, disposalMethod: item.disposalMethod ?? 'Firma prosedürüne göre bertaraf', documentNumber: item.documentNumber, notes: item.notes })); } catch (updateError) { if (updateError instanceof HealthWasteSessionExpiredError) return onSessionExpired(); setError(updateError instanceof Error ? updateError.message : 'Kayıt güncellenemedi.'); } finally { setBusy(false); } };
  const upload = async (file?: File) => { if (!file) return; setBusy(true); setError(null); try { onChanged(await uploadWasteEvidence(token, item.id, file)); } catch (uploadError) { if (uploadError instanceof HealthWasteSessionExpiredError) return onSessionExpired(); setError(uploadError instanceof Error ? uploadError.message : 'Kanıt yüklenemedi.'); } finally { setBusy(false); } };
  return <article className="waste-card"><header><div><span>{item.number}</span><strong>{wasteTypeLabel(item.wasteType)}</strong><small>{item.customerName} · {item.branchName}</small></div><b className={`waste-status status-${item.status.toLowerCase()}`}>{wasteStatusLabel(item.status)}</b></header><div className="waste-amount"><strong>{item.quantity} {item.unit}</strong><span>{formatDate(item.generatedAt)}</span></div>{(item.disposalMethod || item.carrierOrFacility) && <p>{item.disposalMethod ?? 'Yöntem belirtilmedi'}{item.carrierOrFacility ? ` · ${item.carrierOrFacility}` : ''}</p>}<footer>{item.status !== 'Disposed' && <button disabled={busy} onClick={() => void markDisposed()}><CheckCircle2 />Bertaraf edildi</button>}<label><FileUp />Kanıt ekle<input type="file" onChange={(event) => void upload(event.target.files?.[0])} /></label>{item.evidence.map((evidence) => <div key={evidence.id} style={{ display: 'inline-flex', gap: '3px' }}><button onClick={() => void downloadWasteEvidence(token, evidence)} title="İndir"><Download size={14} />{evidence.fileName}</button><button onClick={() => void shareWasteEvidence(token, evidence)} title="Paylaş"><Share2 size={14} /></button></div>)}</footer>{error && <small className="waste-error">{error}</small>}</article>;
}


function WasteModal({ locations, onClose, onSave }: { locations: HealthScoreLocation[]; onClose: () => void; onSave: (input: WasteDisposalInput) => Promise<void> }) {
  const uniqueCustomers = useMemo(() => Array.from(new Map(locations.map((item) => [item.customerId, item.customerName])).entries()), [locations]);
  const [customerId, setCustomerId] = useState(uniqueCustomers[0]?.[0] ?? ''); const [saving, setSaving] = useState(false); const [error, setError] = useState<string | null>(null);
  const branches = locations.filter((item) => item.customerId === customerId);
  const submit = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const data = new FormData(event.currentTarget); setSaving(true); setError(null); try { await onSave({ customerId, branchId: String(data.get('branchId') || '') || undefined, wasteType: String(data.get('wasteType')), quantity: Number(data.get('quantity')), unit: String(data.get('unit')), status: String(data.get('status')), generatedAt: new Date(String(data.get('generatedAt'))).toISOString(), temporaryStorage: value(data, 'temporaryStorage'), recipientName: value(data, 'recipientName'), carrierOrFacility: value(data, 'carrierOrFacility'), disposalMethod: value(data, 'disposalMethod'), documentNumber: value(data, 'documentNumber'), notes: value(data, 'notes') }); } catch (saveError) { setError(saveError instanceof Error ? saveError.message : 'Kayıt oluşturulamadı.'); } finally { setSaving(false); } };
  return <div className="modal-layer"><div className="modal waste-modal"><div className="modal-header"><div><p className="eyebrow">OPSİYONEL İZLENEBİLİRLİK</p><h2>Atık ve bertaraf kaydı</h2><p>İş akışını engellemez; yalnızca ihtiyaç duyduğunuz kayıtları oluşturun.</p></div><button className="icon-button" onClick={onClose}><X /></button></div><form onSubmit={submit}><div className="form-grid"><label>Müşteri<select value={customerId} onChange={(event) => setCustomerId(event.target.value)} required>{uniqueCustomers.map(([id, name]) => <option key={id} value={id}>{name}</option>)}</select></label><label>Şube<select name="branchId"><option value="">Merkez / Genel</option>{branches.filter((item) => item.branchId).map((item) => <option key={item.branchId} value={item.branchId}>{item.branchName}</option>)}</select></label><label>Atık türü<select name="wasteType"><option value="DeadRodent">Ölü kemirgen</option><option value="UsedBait">Kullanılmış yem</option><option value="EmptyChemicalContainer">Boş kimyasal ambalaj</option><option value="DamagedStation">Hasarlı istasyon</option><option value="GlueBoard">Yapışkan plaka</option><option value="UvLamp">UV lamba</option><option value="ContaminatedPpe">Kontamine koruyucu ekipman</option><option value="Other">Diğer</option></select></label><label>Durum<select name="status"><option value="Generated">Oluştu</option><option value="Stored">Geçici depoda</option><option value="Transferred">Teslim edildi</option><option value="Disposed">Bertaraf edildi</option></select></label><label>Miktar<input name="quantity" type="number" min="0.001" step="0.001" required /></label><label>Birim<select name="unit"><option value="Adet">Adet</option><option value="kg">kg</option><option value="g">g</option><option value="Litre">Litre</option></select></label><label>Oluşma tarihi<input name="generatedAt" type="datetime-local" defaultValue={toLocalInput(new Date())} required /></label><label>Geçici depolama<input name="temporaryStorage" placeholder="Opsiyonel" /></label><label>Teslim alan<input name="recipientName" placeholder="Opsiyonel" /></label><label>Taşıyıcı / tesis<input name="carrierOrFacility" placeholder="Opsiyonel" /></label><label>Bertaraf yöntemi<input name="disposalMethod" placeholder="Opsiyonel" /></label><label>Belge / makbuz no<input name="documentNumber" placeholder="Opsiyonel" /></label><label className="form-field-wide">Notlar<textarea name="notes" rows={3} placeholder="Opsiyonel açıklama" /></label></div>{error && <div className="modal-form-error">{error}</div>}<div className="modal-actions"><button type="button" className="secondary-button" onClick={onClose}>Vazgeç</button><button className="primary-button" disabled={saving}><Archive size={16} />{saving ? 'Kaydediliyor…' : 'Opsiyonel kaydı oluştur'}</button></div></form></div></div>;
}

const value = (data: FormData, key: string) => String(data.get(key) || '').trim() || undefined;
const toLocalInput = (date: Date) => new Date(date.getTime() - date.getTimezoneOffset() * 60000).toISOString().slice(0, 16);
const formatDate = (value: string) => new Intl.DateTimeFormat('tr-TR', { day: '2-digit', month: 'short', year: 'numeric', hour: '2-digit', minute: '2-digit' }).format(new Date(value));
const healthLevel = (value: string) => ({ Low: 'İyi', Medium: 'İzlenmeli', High: 'Yüksek risk' } as Record<string, string>)[value] ?? value;
const confidenceLabel = (value: string) => ({ Low: 'Düşük veri', Medium: 'Orta', High: 'Yüksek' } as Record<string, string>)[value] ?? value;
const wasteTypeLabel = (value: string) => ({ DeadRodent: 'Ölü kemirgen', UsedBait: 'Kullanılmış yem', EmptyChemicalContainer: 'Boş kimyasal ambalaj', DamagedStation: 'Hasarlı istasyon', GlueBoard: 'Yapışkan plaka', UvLamp: 'UV lamba', ContaminatedPpe: 'Kontamine koruyucu ekipman', Other: 'Diğer' } as Record<string, string>)[value] ?? value;
const wasteStatusLabel = (value: string) => ({ Generated: 'Oluştu', Stored: 'Geçici depoda', Transferred: 'Teslim edildi', Disposed: 'Bertaraf edildi' } as Record<string, string>)[value] ?? value;
