import { useEffect, useMemo, useState, type FormEvent } from 'react';
import { AlertTriangle, Award, BarChart3, CheckCircle2, ClipboardCheck, FileCheck2, Plus, Search, ShieldAlert, Sparkles, X } from 'lucide-react';
import { completeQualityInspection, createQualityInspection, getQualityInspectionCandidates, getQualityInspections, getQualityInspectionSummary, QualityInspectionSessionExpiredError, type QualityGrade, type QualityInspection, type QualityInspectionCandidate, type QualityInspectionSummary, type QualityInspectionType } from '../../services/qualityInspectionApi';

const gradeLabels: Record<QualityGrade, string> = { Pending: 'Bekliyor', Excellent: 'Mükemmel', Good: 'İyi', Acceptable: 'Kabul edilebilir', NeedsImprovement: 'Geliştirilmeli', Critical: 'Kritik' };
const typeLabels: Record<QualityInspectionType, string> = { Random: 'Rastgele kontrol', ManagerVisit: 'Yönetici saha ziyareti', RiskBased: 'Risk bazlı kontrol', ComplaintFollowUp: 'Şikâyet sonrası kontrol', SecondControl: 'İkinci kontrol' };

export default function QualityInspectionCenter({ accessToken, onSessionExpired }: { accessToken: string; onSessionExpired: () => void }) {
  const [items, setItems] = useState<QualityInspection[]>([]); const [summary, setSummary] = useState<QualityInspectionSummary | null>(null); const [candidates, setCandidates] = useState<QualityInspectionCandidate[]>([]);
  const [loading, setLoading] = useState(true); const [error, setError] = useState<string | null>(null); const [creating, setCreating] = useState(false); const [scoring, setScoring] = useState<QualityInspection | null>(null); const [view, setView] = useState<'open' | 'completed' | 'employees'>('open');
  const load = async () => { setLoading(true); setError(null); try { const [records, summaryData, candidateData] = await Promise.all([getQualityInspections(accessToken), getQualityInspectionSummary(accessToken), getQualityInspectionCandidates(accessToken)]); setItems(records); setSummary(summaryData); setCandidates(candidateData); } catch (loadError) { if (loadError instanceof QualityInspectionSessionExpiredError) return onSessionExpired(); setError(loadError instanceof Error ? loadError.message : 'Kalite kontrolleri yüklenemedi.'); } finally { setLoading(false); } };
  useEffect(() => { void load(); }, [accessToken]);
  const visible = useMemo(() => view === 'open' ? items.filter((item) => item.status !== 'Completed') : items.filter((item) => item.status === 'Completed'), [items, view]);
  return <div className="quality-inspection-center">
    <div className="quality-inspection-actions"><div><p className="eyebrow">İKİNCİ KONTROL & PERSONEL KALİTESİ</p><h2>Veriye dayalı saha denetimi</h2><span>Personeli yalnızca iş sayısıyla değil, uygulama ve kayıt kalitesiyle değerlendirin.</span></div><button className="btn btn-primary" onClick={() => setCreating(true)}><Plus size={18} />Kontrol planla</button></div>
    <div className="inspection-kpis"><Kpi icon={<ClipboardCheck />} label="Açık kontrol" value={summary?.openCount ?? 0} tone="blue" /><Kpi icon={<CheckCircle2 />} label="Tamamlanan" value={summary?.completedCount ?? 0} tone="green" /><Kpi icon={<Award />} label="Ortalama kalite" value={summary?.averageScore == null ? '—' : `${summary.averageScore}/100`} tone="purple" /><Kpi icon={<ShieldAlert />} label="Faaliyet açılan" value={summary?.correctiveActionCount ?? 0} tone="orange" /></div>
    <div className="inspection-tabs"><button className={view === 'open' ? 'active' : ''} onClick={() => setView('open')}>Bekleyen kontroller</button><button className={view === 'completed' ? 'active' : ''} onClick={() => setView('completed')}>Tamamlananlar</button><button className={view === 'employees' ? 'active' : ''} onClick={() => setView('employees')}>Personel kalite skoru</button></div>
    {error && <div className="quality-error"><AlertTriangle />{error}<button onClick={() => void load()}>Tekrar dene</button></div>}
    {loading ? <div className="surface inspection-empty"><Sparkles className="spin-icon" /><strong>Kalite verileri hazırlanıyor…</strong></div> : view === 'employees' ? <EmployeeScores summary={summary} /> : visible.length === 0 ? <div className="surface inspection-empty"><FileCheck2 /><strong>{view === 'open' ? 'Bekleyen ikinci kontrol bulunmuyor' : 'Tamamlanmış kontrol bulunmuyor'}</strong><span>Yayınlanmış saha raporlarından risk bazlı veya rastgele kontrol planlayabilirsiniz.</span></div> : <div className="inspection-grid">{visible.map((item) => <InspectionCard key={item.id} item={item} onScore={() => setScoring(item)} />)}</div>}
    {creating && <CreateInspectionModal candidates={candidates} onClose={() => setCreating(false)} onSave={async (input) => { await createQualityInspection(accessToken, input); setCreating(false); await load(); }} />}
    {scoring && <ScoreInspectionModal item={scoring} onClose={() => setScoring(null)} onSave={async (input) => { await completeQualityInspection(accessToken, scoring.id, input); setScoring(null); await load(); }} />}
  </div>;
}

function Kpi({ icon, label, value, tone }: { icon: React.ReactNode; label: string; value: string | number; tone: string }) { return <article><span className={tone}>{icon}</span><div><small>{label}</small><strong>{value}</strong></div></article>; }
function InspectionCard({ item, onScore }: { item: QualityInspection; onScore: () => void }) { return <article className="surface inspection-card"><header><span>{item.number}</span><b className={`grade-${item.grade.toLowerCase()}`}>{item.status === 'Completed' ? gradeLabels[item.grade] : typeLabels[item.inspectionType]}</b></header><h3>{item.customerName}</h3><p>{item.branchName} · {item.reportNumber}</p><dl><div><dt>Personel</dt><dd>{item.employeeName}</dd></div><div><dt>Seçim nedeni</dt><dd>{item.selectionReason}</dd></div>{item.status === 'Completed' && <><div><dt>Kalite puanı</dt><dd>{item.totalScore}/100</dd></div><div><dt>Düzeltici faaliyet</dt><dd>{item.correctiveActionNumber ?? 'Gerekmedi'}</dd></div></>}</dl>{item.findings && <blockquote>{item.findings}</blockquote>}<footer>{item.status !== 'Completed' ? <button className="btn btn-primary" onClick={onScore}>Kontrolü tamamla</button> : <span><CheckCircle2 />{formatDate(item.inspectedAt)}</span>}</footer></article>; }
function EmployeeScores({ summary }: { summary: QualityInspectionSummary | null }) { return <div className="surface employee-quality-table"><header><div><BarChart3 /><span><strong>Personel kalite sıralaması</strong><small>Sonuç; fotoğraf, istasyon, doz, imza, zamanlama ve rapor kalitesinden oluşur.</small></span></div></header><div>{summary?.employees.map((employee, index) => <article key={employee.employeeAccountId}><b>{index + 1}</b><span><strong>{employee.employeeName}</strong><small>{employee.inspectionCount} denetim</small></span><div><em>{employee.averageScore == null ? '—' : `${employee.averageScore}/100`}</em><i className={`grade-${employee.grade.toLowerCase()}`}>{gradeLabels[employee.grade]}</i></div></article>)}</div></div>; }

function CreateInspectionModal({ candidates, onClose, onSave }: { candidates: QualityInspectionCandidate[]; onClose: () => void; onSave: (input: { serviceReportId: string; inspectionType: QualityInspectionType; selectionReason: string; scheduledAt?: string }) => Promise<void> }) {
  const [query, setQuery] = useState(''); const [selected, setSelected] = useState<QualityInspectionCandidate | null>(candidates.find((item) => item.recommended) ?? candidates[0] ?? null); const [type, setType] = useState<QualityInspectionType>(selected?.recommended ? 'RiskBased' : 'SecondControl'); const [reason, setReason] = useState(selected?.recommendationReason ?? 'Yönetici ikinci kontrolü'); const [scheduledAt, setScheduledAt] = useState(''); const [saving, setSaving] = useState(false); const [error, setError] = useState<string | null>(null);
  const filtered = candidates.filter((item) => `${item.customerName} ${item.branchName} ${item.reportNumber} ${item.employeeName}`.toLocaleLowerCase('tr-TR').includes(query.toLocaleLowerCase('tr-TR')));
  const submit = async (event: FormEvent) => { event.preventDefault(); if (!selected) return; setSaving(true); setError(null); try { await onSave({ serviceReportId: selected.serviceReportId, inspectionType: type, selectionReason: reason, scheduledAt: scheduledAt ? new Date(scheduledAt).toISOString() : undefined }); } catch (saveError) { setError(saveError instanceof Error ? saveError.message : 'Kontrol planlanamadı.'); setSaving(false); } };
  return <div className="modal-layer"><div className="modal inspection-modal"><div className="modal-header"><div className="quality-modal-icon"><ClipboardCheck /></div><div><p className="eyebrow">KALİTE KONTROL</p><h2>Yeni ikinci kontrol</h2><span>Yayınlanmış bir saha raporunu kalite örneklemine alın.</span></div><button className="icon-button" onClick={onClose}><X /></button></div><form onSubmit={submit}><div className="modal-body"><label className="inspection-search"><Search /><input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Müşteri, rapor veya personel ara" /></label><div className="candidate-list">{filtered.map((item) => <button type="button" key={item.serviceReportId} className={selected?.serviceReportId === item.serviceReportId ? 'active' : ''} onClick={() => { setSelected(item); setReason(item.recommendationReason); setType(item.recommended ? 'RiskBased' : 'SecondControl'); }}><span><strong>{item.customerName} · {item.branchName}</strong><small>{item.reportNumber} · {item.employeeName}</small></span><div>{item.recommended && <b>Önerilen</b>}<em>{item.preliminaryScore}/100</em></div><p>{item.recommendationReason} · {item.stationCount} istasyon · {item.photoCount} fotoğraf</p></button>)}</div>{candidates.length === 0 && <div className="inspection-empty compact"><span>Kontrole uygun yayınlanmış rapor bulunmuyor.</span></div>}<div className="form-grid"><label>Kontrol türü<select value={type} onChange={(e) => setType(e.target.value as QualityInspectionType)}>{Object.entries(typeLabels).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></label><label>Planlanan tarih<input type="datetime-local" value={scheduledAt} onChange={(e) => setScheduledAt(e.target.value)} /></label><label className="span-2">Seçim nedeni<input required value={reason} onChange={(e) => setReason(e.target.value)} /></label></div>{error && <div className="form-error">{error}</div>}</div><div className="modal-actions"><button type="button" className="btn btn-outline" onClick={onClose}>Vazgeç</button><button className="btn btn-primary" disabled={!selected || saving}>{saving ? 'Planlanıyor…' : 'Kontrolü planla'}</button></div></form></div></div>;
}

const scoreFields = [['photoQualityScore','Fotoğraf kalitesi','%15'],['stationCompletionScore','İstasyon tamamlama','%25'],['productDoseScore','Ürün ve doz doğruluğu','%20'],['signatureScore','Müşteri imzası','%15'],['timelinessScore','Zamanlama ve tekrar ziyaret','%10'],['reportCompletenessScore','Rapor veri bütünlüğü','%15']] as const;
function ScoreInspectionModal({ item, onClose, onSave }: { item: QualityInspection; onClose: () => void; onSave: (input: Record<typeof scoreFields[number][0], number> & { findings?: string; notes?: string; createCorrectiveAction: boolean }) => Promise<void> }) {
  const [scores, setScores] = useState<Record<typeof scoreFields[number][0], number>>({ photoQualityScore: 80, stationCompletionScore: 80, productDoseScore: 80, signatureScore: 80, timelinessScore: 80, reportCompletenessScore: 80 }); const [findings, setFindings] = useState(''); const [notes, setNotes] = useState(''); const [createAction, setCreateAction] = useState(false); const [saving, setSaving] = useState(false); const [error, setError] = useState<string | null>(null);
  const total = Math.round(scores.photoQualityScore * .15 + scores.stationCompletionScore * .25 + scores.productDoseScore * .20 + scores.signatureScore * .15 + scores.timelinessScore * .10 + scores.reportCompletenessScore * .15);
  const submit = async (event: FormEvent) => { event.preventDefault(); setSaving(true); setError(null); try { await onSave({ ...scores, findings: findings || undefined, notes: notes || undefined, createCorrectiveAction: createAction }); } catch (saveError) { setError(saveError instanceof Error ? saveError.message : 'Kontrol tamamlanamadı.'); setSaving(false); } };
  return <div className="modal-layer"><div className="modal inspection-modal score-modal"><div className="modal-header"><div className="quality-modal-icon"><Award /></div><div><p className="eyebrow">{item.number}</p><h2>Kalite puanlaması</h2><span>{item.customerName} · {item.employeeName}</span></div><button className="icon-button" onClick={onClose}><X /></button></div><form onSubmit={submit}><div className="modal-body"><div className="score-overview"><span className={`grade-${gradeFromScore(total).toLowerCase()}`}><strong>{total}</strong><small>/100 · {gradeLabels[gradeFromScore(total)]}</small></span><p>Puan 70’in altında kalırsa sistem otomatik düzeltici faaliyet açar.</p></div><div className="score-grid">{scoreFields.map(([key, label, weight]) => <label key={key}><span><strong>{label}</strong><small>Ağırlık {weight}</small></span><input type="range" min="0" max="100" step="5" value={scores[key]} onChange={(e) => setScores((current) => ({ ...current, [key]: Number(e.target.value) }))} /><b>{scores[key]}</b></label>)}</div><div className="form-grid"><label className="span-2">Bulgular<textarea rows={3} value={findings} onChange={(e) => setFindings(e.target.value)} placeholder="Eksik veri, yanlış uygulama veya olumlu kalite bulgularını yazın." /></label><label className="span-2">Denetçi notu<textarea rows={2} value={notes} onChange={(e) => setNotes(e.target.value)} /></label></div><label className="inspection-check"><input type="checkbox" checked={createAction} onChange={(e) => setCreateAction(e.target.checked)} /><span><strong>Düzeltici faaliyet aç</strong><small>Puan yeterli olsa bile bulgu için takip kaydı oluşturur.</small></span></label>{error && <div className="form-error">{error}</div>}</div><div className="modal-actions"><button type="button" className="btn btn-outline" onClick={onClose}>Vazgeç</button><button className="btn btn-primary" disabled={saving}>{saving ? 'Kaydediliyor…' : 'Kontrolü tamamla'}</button></div></form></div></div>;
}
const gradeFromScore = (score: number): QualityGrade => score >= 90 ? 'Excellent' : score >= 80 ? 'Good' : score >= 70 ? 'Acceptable' : score >= 50 ? 'NeedsImprovement' : 'Critical';
const formatDate = (value?: string) => value ? new Intl.DateTimeFormat('tr-TR', { dateStyle: 'medium' }).format(new Date(value)) : '—';
