namespace Pesneer.Api.Reports;

public sealed record ServiceReportPestObservationInput(
    string PestKey,
    string PestName,
    int DetectedCount,
    int ApprovedCount,
    decimal MeanConfidence,
    string Source,
    string? ModelName,
    string? ModelVersion,
    string ReviewStatus,
    string? VisionResultJson,
    DateTimeOffset? AnalyzedAt);

public sealed record ServiceReportStationInput(
    Guid? SitePlanId,
    string? SitePlanElementId,
    string DeviceNumber,
    string Area,
    string DeviceType,
    string? TargetPest,
    int CaughtCount,
    bool HasActivity,
    bool PlateChanged,
    string DeviceStatus,
    string? ActivityType,
    string? InaccessibilityReason,
    Guid? AppliedVehicleStockItemId,
    string? AppliedProductName,
    decimal? AppliedAmount,
    string? AppliedUnit,
    Guid? ReplacementVehicleStockItemId,
    string? ReplacementProductName,
    decimal? ReplacementQuantity,
    string? ReplacementUnit,
    string? Notes,
    IReadOnlyList<ServiceReportPestObservationInput>? PestObservations,
    bool BaitGelCompleted = false,
    bool StickyPlateChanged = false,
    bool StationCleaned = false,
    bool StationRelocated = false,
    bool StationReplaced = false,
    bool LockCheckDone = false,
    bool LabelRenewed = false);

public sealed record ServiceReportProductInput(
    Guid? VehicleStockItemId,
    Guid? LicenseDocumentId,
    string ProductName,
    string? LicenseNumber,
    string? ApplicationMethod,
    string? DilutionRate,
    string? ActiveIngredient,
    string? Antidote,
    string? PackingQuantity,
    decimal AmountUsed,
    string Unit);

public sealed record UpsertServiceReportRequest(
    string FirmName,
    string? FirmAddress,
    string? FirmPhone,
    string? FirmWeb,
    string? ResponsibleManager,
    string? PermissionNumber,
    string? TeamManager,
    string? TargetPests,
    string? ResidenceType,
    decimal? AreaSquareMeters,
    string? WorkType,
    string? Consumables,
    string? SafetyMeasures,
    string? ApplicationSummary,
    string? Findings,
    string? CorrectiveActions,
    string? Recommendations,
    string? CustomerRepresentativeName,
    string? ManagerSignatureData,
    string? CustomerSignatureData,
    IReadOnlyList<string>? AdditionalEmailRecipients,
    DateTimeOffset? BaseUpdatedAt,
    bool ForceOverwrite,
    bool Finalize,
    IReadOnlyList<ServiceReportStationInput> Stations,
    IReadOnlyList<ServiceReportProductInput> Products);

public sealed record ServiceReportStationResponse(
    Guid Id,
    Guid? SitePlanId,
    string? SitePlanElementId,
    string DeviceNumber,
    string Area,
    string DeviceType,
    string? TargetPest,
    int CaughtCount,
    bool HasActivity,
    bool PlateChanged,
    string DeviceStatus,
    string? ActivityType,
    string? InaccessibilityReason,
    Guid? AppliedVehicleStockItemId,
    string? AppliedProductName,
    decimal? AppliedAmount,
    string? AppliedUnit,
    Guid? ReplacementVehicleStockItemId,
    string? ReplacementProductName,
    decimal? ReplacementQuantity,
    string? ReplacementUnit,
    string? Notes,
    IReadOnlyList<ServiceReportPestObservationResponse> PestObservations);

public sealed record ServiceReportPestObservationResponse(
    Guid Id,
    string PestKey,
    string PestName,
    int DetectedCount,
    int ApprovedCount,
    decimal MeanConfidence,
    string Source,
    string? ModelName,
    string? ModelVersion,
    string ReviewStatus,
    DateTimeOffset? AnalyzedAt,
    DateTimeOffset? ReviewedAt);

public sealed record ServiceReportProductResponse(
    Guid Id,
    Guid? VehicleStockItemId,
    Guid? LicenseDocumentId,
    string ProductName,
    string? LicenseNumber,
    string? ApplicationMethod,
    string? DilutionRate,
    string? ActiveIngredient,
    string? Antidote,
    string? PackingQuantity,
    decimal AmountUsed,
    string Unit);

public sealed record ServiceReportPhotoResponse(Guid Id, string FileName, string ContentType, DateTimeOffset UploadedAt, string Url, string? Location, string? Status, string? Description);

public sealed record ServiceReportResponse(
    Guid Id,
    Guid WorkOrderId,
    string WorkOrderNumber,
    string ReportNumber,
    string Status,
    Guid CustomerId,
    string CustomerName,
    Guid? BranchId,
    string BranchName,
    string BranchAddress,
    DateTimeOffset ScheduledAt,
    DateTimeOffset? StartedAt,
    DateTimeOffset? CompletedAt,
    int? CustomerDurationMinutes,
    int TotalLaborMinutes,
    string OperatorName,
    string FirmName,
    string? FirmAddress,
    string? FirmPhone,
    string? FirmWeb,
    string? ResponsibleManager,
    string? PermissionNumber,
    string? TeamManager,
    string? TargetPests,
    string? ResidenceType,
    decimal? AreaSquareMeters,
    string? WorkType,
    string? Consumables,
    string? SafetyMeasures,
    string? ApplicationSummary,
    string? Findings,
    string? CorrectiveActions,
    string? Recommendations,
    string? CustomerRepresentativeName,
    string? ManagerSignatureData,
    string? CustomerSignatureData,
    string VerificationCode,
    DateTimeOffset UpdatedAt,
    DateTimeOffset? FinalizedAt,
    int TotalStations,
    int ActiveStations,
    int PlateChanges,
    int TotalCaught,
    decimal ActivityRate,
    int RiskScore,
    string RiskLevel,
    bool InfestationIndicator,
    IReadOnlyList<string> AdditionalEmailRecipients,
    string EmailDeliveryStatus,
    int EmailSentCount,
    int EmailRecipientCount,
    IReadOnlyList<ServiceReportStationResponse> Stations,
    IReadOnlyList<ServiceReportProductResponse> Products,
    IReadOnlyList<ServiceReportPhotoResponse> Photos);

public sealed record ServiceReportSummaryResponse(
    Guid Id,
    Guid WorkOrderId,
    string WorkOrderNumber,
    string ReportNumber,
    string Status,
    Guid CustomerId,
    string CustomerName,
    Guid? BranchId,
    string BranchName,
    DateTimeOffset ScheduledAt,
    string OperatorName,
    DateTimeOffset UpdatedAt,
    DateTimeOffset? FinalizedAt,
    int TotalStations,
    int ActiveStations,
    int PlateChanges,
    int TotalCaught,
    decimal ActivityRate,
    int RiskScore,
    string RiskLevel,
    bool InfestationIndicator,
    string EmailDeliveryStatus,
    int EmailSentCount,
    int EmailRecipientCount,
    string DetailUrl,
    string PdfUrl);

public sealed record TrendPeriodResponse(
    string Period,
    int ReportCount,
    int TotalStations,
    int ActiveStations,
    int PlateChanges,
    int TotalCaught,
    decimal ActivityRate,
    int RiskScore,
    string RiskLevel);

public sealed record PestTrendResponse(string Pest, int TotalCaught);

public sealed record ServiceReportAnalyticsResponse(
    DateOnly From,
    DateOnly To,
    int ReportCount,
    int TotalStations,
    int ActiveStations,
    int TotalCaught,
    decimal ActivityRate,
    int RiskScore,
    string RiskLevel,
    IReadOnlyList<TrendPeriodResponse> Periods,
    IReadOnlyList<PestTrendResponse> PestTotals);
