import { useEffect, useMemo, useState } from 'react';
import { AlertTriangle, CheckCircle2, ChevronDown, ChevronUp, Clock3, MessageSquare, RefreshCw, Send, ShieldAlert, UserCheck } from 'lucide-react';
import type { EmployeeRecord } from '../services/employeeApi';
import { addCompanyRequestMessage, CustomerPortalSessionExpiredError, getCompanyEmergencyRequests, updateCompanyEmergencyRequest, type EmergencyRequestRecord } from '../services/customerPortalApi';

export default function RequestCenter({ accessToken, employees, onSessionExpired }: { accessToken: string; employees: EmployeeRecord[]; onSessionExpired: () => void }) {
  const [items, setItems] = useState<EmergencyRequestRecord[]>([]); const [selected, setSelected] = useState<EmergencyRequestRecord | null>(null); const [loading, setLoading] = useState(true); const [error, setError] = useState<string | null>(null); const [filter, setFilter] = useState('Open'); const [listExpanded, setListExpanded] = useState(false);
  const load = async () => { setLoading(true); setError(null); try { setItems(await getCompanyEmergencyRequests(accessToken)); } catch (cause) { if (cause instanceof CustomerPortalSessionExpiredError) return onSessionExpired(); setError(cause instanceof Error ? cause.message : 'Talepler yüklenemedi.'); } finally { setLoading(false); } };
  useEffect(() => { void load(); }, [accessToken]);
  const visible = useMemo(() => items.filter((item) => filter === 'All' || filter === 'Open' && !['Completed','Cancelled'].includes(item.status) || item.requestType === filter), [items, filter]);
  const save = async (item: EmergencyRequestRecord, input: { status: string; employeeAccountId?: string; note?: string; dueAt?: string }) => { try { const updated = await updateCompanyEmergencyRequest(accessToken, item.id, input); setItems((current) => current.map((value) => value.id === updated.id ? updated : value)); setSelected((current) => current?.id === updated.id ? updated : current); } catch (cause) { setError(cause instanceof Error ? cause.message : 'Talep güncellenemedi.'); } };
  const message = async (text: string) => { if (!selected || !text.trim()) return; const updated = await addCompanyRequestMessage(accessToken, selected.id, text); setItems((current) => current.map((value) => value.id === updated.id ? updated : value)); setSelected(updated); };
  const openCount = items.filter((item) => !['Completed','Cancelled'].includes(item.status)).length;
  const selectRequest = (item: EmergencyRequestRecord) => { setSelected(item); setListExpanded(false); };
  return <section className="page request-center-page"><div className="page-heading"><div><p className="eyebrow">MÜŞTERİ DENEYİMİ & SLA</p><h1>Talep ve Şikâyet Merkezi</h1><p>Acil çağrı, şikâyet, belge, yeni şube ve randevu taleplerini sorumlu, termin ve kapanış onayıyla yönetin.</p></div><button className="secondary-button" onClick={() => void load()}><RefreshCw size={17} /> Yenile</button></div>
    <div className="commercial-kpis"><Kpi label="Açık talep" value={openCount} tone="blue" /><Kpi label="Kritik" value={items.filter((item) => item.priority === 'Critical' && !['Completed','Cancelled'].includes(item.status)).length} tone="red" /><Kpi label="Onay bekleyen" value={items.filter((item) => item.closureApprovalStatus === 'Pending').length} tone="orange" /><Kpi label="Kapanan" value={items.filter((item) => item.status === 'Completed').length} tone="green" /></div>
    <div className={`request-workspace surface ${selected ? 'has-selection' : 'is-empty'}`}><aside className={listExpanded ? 'is-expanded' : ''}><div className="request-filters">{requestFilters.map((item) => <button className={filter === item.value ? 'active' : ''} key={item.value} onClick={() => setFilter(item.value)}>{item.label}</button>)}</div><div className="request-list-scroll">{loading ? <div className="commercial-empty request-list-empty"><RefreshCw className="spin-icon" /> Yükleniyor…</div> : visible.map((item) => <button className={`request-list-item ${selected?.id === item.id ? 'active' : ''}`} key={item.id} onClick={() => selectRequest(item)}><span className={`request-priority ${item.priority.toLowerCase()}`} /><div><strong>{item.subject}</strong><small>{item.customerName} · {item.branchName}</small><em>{item.number} · {typeLabel(item.requestType)}</em></div><b>{statusLabel(item.status)}</b></button>)}{!loading && visible.length === 0 && <div className="commercial-empty request-list-empty">Kayıt bulunmuyor.</div>}</div>{!loading && visible.length > 2 && <button type="button" className="request-list-expand" onClick={() => setListExpanded((value) => !value)} aria-expanded={listExpanded}>{listExpanded ? <><ChevronUp size={15} /> Listeyi daralt</> : <><ChevronDown size={15} /> Listeyi genişlet ({visible.length})</>}</button>}</aside>
      <div className={`request-detail ${selected ? 'has-item' : ''}`}>{error && <div className="field-operation-error"><AlertTriangle size={15} />{error}</div>}{selected ? <RequestDetail item={selected} employees={employees} onSave={save} onMessage={message} /> : <div className="request-detail-empty"><MessageSquare size={22} /><strong>Talep seçin</strong><span>Mesaj geçmişi, sorumlu, termin ve kapanış süreci burada açılır.</span></div>}</div></div>
  </section>;
}

function RequestDetail({ item, employees, onSave, onMessage }: { item: EmergencyRequestRecord; employees: EmployeeRecord[]; onSave: (item: EmergencyRequestRecord, input: { status: string; employeeAccountId?: string; note?: string; dueAt?: string }) => Promise<void>; onMessage: (message: string) => Promise<void> }) {
  const [text, setText] = useState('');
  return <><header><div><span>{item.number} · {typeLabel(item.requestType)}</span><h2>{item.subject}</h2><p>{item.customerName} · {item.branchName}</p></div><em className={`request-status status-${item.status.toLowerCase()}`}>{statusLabel(item.status)}</em></header>
    <div className="request-meta-grid"><label><UserCheck size={15} /> Sorumlu<select value={item.assignedEmployeeAccountId ?? ''} onChange={(event) => void onSave(item, { status: item.status, employeeAccountId: event.target.value || undefined, note: 'Talep sorumlusu güncellendi.' })}><option value="">Atama bekliyor</option>{employees.filter((employee) => employee.isActive).map((employee) => <option key={employee.id} value={employee.id}>{employee.name}</option>)}</select></label><label><Clock3 size={15} /> Termin<input type="datetime-local" defaultValue={item.dueAt?.slice(0,16)} onBlur={(event) => event.target.value && void onSave(item, { status: item.status, employeeAccountId: item.assignedEmployeeAccountId, dueAt: new Date(event.target.value).toISOString(), note: 'Termin güncellendi.' })} /></label></div>
    <div className="request-description"><strong>Talep açıklaması</strong><p>{item.description}</p>{item.requestedAppointmentAt && <span>Talep edilen randevu: {formatDate(item.requestedAppointmentAt)}</span>}</div>
    <div className="request-actions"><button onClick={() => void onSave(item, { status: 'Acknowledged', employeeAccountId: item.assignedEmployeeAccountId, note: 'Talep firma tarafından kabul edildi.' })}>Kabul et</button><button onClick={() => void onSave(item, { status: 'InProgress', employeeAccountId: item.assignedEmployeeAccountId, note: 'Talep işleme alındı.' })}>İşleme al</button><button className="complete" onClick={() => void onSave(item, { status: 'AwaitingCustomerApproval', employeeAccountId: item.assignedEmployeeAccountId, note: 'İşlem tamamlandı, müşteri kapanış onayına gönderildi.' })}><CheckCircle2 size={14} /> Onaya gönder</button></div>
    <section className="request-thread"><h3><MessageSquare size={16} /> Mesaj ve işlem geçmişi</h3>{item.history.map((history, index) => <article key={`${history.occurredAt}-${index}`}><span>{history.changedBy.slice(0,1)}</span><div><strong>{history.changedBy}<em>{statusLabel(history.status)}</em></strong><p>{history.note || 'Durum güncellendi.'}</p><small>{formatDate(history.occurredAt)}</small></div></article>)}</section>
    <form className="request-message-box" onSubmit={(event) => { event.preventDefault(); void onMessage(text).then(() => setText('')); }}><input value={text} onChange={(event) => setText(event.target.value)} placeholder="Müşteriye veya personele mesaj yazın…" /><button disabled={!text.trim()}><Send size={16} /></button></form>
  </>;
}
function Kpi({ label, value, tone }: { label: string; value: number; tone: string }) { return <article className={`commercial-kpi ${tone}`}><span><ShieldAlert /></span><div><small>{label}</small><strong>{value}</strong></div></article>; }
const requestFilters = [{ value: 'Open', label: 'Açık talepler' }, { value: 'EmergencyCall', label: 'Acil çağrı' }, { value: 'Complaint', label: 'Şikâyet' }, { value: 'NewBranch', label: 'Yeni şube' }, { value: 'AppointmentChange', label: 'Randevu' }, { value: 'DocumentRequest', label: 'Belge' }, { value: 'StructuralCompletion', label: 'Yapısal faaliyet' }, { value: 'All', label: 'Tümü' }];
function typeLabel(value: string) { return ({ EmergencyCall: 'Acil çağrı', Complaint: 'Şikâyet', NewBranch: 'Yeni şube talebi', AppointmentChange: 'Randevu değişikliği', DocumentRequest: 'Belge talebi', StructuralCompletion: 'Yapısal faaliyet' } as Record<string,string>)[value] ?? value; }
function statusLabel(value: string) { return ({ New:'Yeni', Acknowledged:'Kabul edildi', Planned:'Planlandı', InProgress:'İşlemde', AwaitingCustomerApproval:'Müşteri onayında', Completed:'Kapandı', Cancelled:'İptal' } as Record<string,string>)[value] ?? value; }
function formatDate(value: string) { return new Intl.DateTimeFormat('tr-TR', { dateStyle: 'short', timeStyle: 'short' }).format(new Date(value)); }
