import { useMemo, useState } from 'react';
import { Activity, AlertCircle, Building2, Eye, ExternalLink, MapPinned, Pencil, Plus, RefreshCw, Search, Store } from 'lucide-react';
import type { WorkOrder } from '../types';
import type { CustomerRecord } from '../services/workOrderApi';
import StatusBadge from '../components/common/StatusBadge';
import OwnerEmergencyRequests from '../components/workorders/OwnerEmergencyRequests';
import type { EmployeeRecord } from '../services/employeeApi';

type Props = { accessToken: string; employees: EmployeeRecord[]; onSessionExpired: () => void; workOrders: WorkOrder[]; customers: CustomerRecord[]; isLoading: boolean; loadError: string | null; onReload: () => void; onCreate: () => void; onManageCustomers: () => void; onEdit: (order: WorkOrder) => void; onView: (order: WorkOrder) => void };

export default function WorkOrders({ accessToken, employees, onSessionExpired, workOrders, customers, isLoading, loadError, onReload, onCreate, onManageCustomers, onEdit, onView }: Props) {
  const [query, setQuery] = useState(''); const [status, setStatus] = useState('all');
  const totalBranches = customers.reduce((sum, customer) => sum + customer.branches.length, 0);
  const filteredOrders = useMemo(() => { const normalized = query.trim().toLocaleLowerCase('tr-TR'); return workOrders.filter((order) => (!normalized || `${order.id} ${order.client} ${order.branch} ${order.technician} ${order.service}`.toLocaleLowerCase('tr-TR').includes(normalized)) && (status === 'all' || order.status === status)); }, [workOrders, query, status]);

  return <section className="page work-orders-page">
    <div className="page-heading"><div><p className="eyebrow">OPERASYON YÖNETİMİ</p><h1>İş emirleri</h1><p>Çok şubeli müşteri planlarını, personel atamalarını ve saha kapanışlarını yönetin.</p></div><div className="page-heading-actions"><button className="secondary-button" onClick={onManageCustomers}><Building2 size={18} /> Müşteri & Şube</button><button className="primary-button" onClick={onCreate}><Plus size={19} /> Yeni iş emri</button></div></div>
    <div className="work-order-kpis"><article className="surface"><span><Building2 size={19} /></span><div><small>Kurumsal müşteri</small><strong>{customers.length}</strong><em>Çatı firma kaydı</em></div></article><article className="surface"><span className="green"><Store size={19} /></span><div><small>Tanımlı şube</small><strong>{totalBranches}</strong><em>Bağımsız konum ve iletişim</em></div></article><article className="surface"><span className="orange"><Activity size={19} /></span><div><small>Aktif iş emri</small><strong>{workOrders.filter((item) => item.technicalStatus !== 'Completed' && item.technicalStatus !== 'Cancelled').length}</strong><em>Planlanan ve sahadaki</em></div></article></div>
    <OwnerEmergencyRequests accessToken={accessToken} employees={employees} onSessionExpired={onSessionExpired} />
    <section className="surface toolbar-surface"><div className="toolbar"><div className="search-field"><Search size={18} /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="İş emri, müşteri, şube veya personel ara" /></div><label className="toolbar-select"><Activity size={17} /><select value={status} onChange={(event) => setStatus(event.target.value)}><option value="all">Tüm durumlar</option><option value="Planlandı">Planlandı</option><option value="Sahada">Sahada</option><option value="Tamamlandı">Tamamlandı</option><option value="İptal">İptal</option></select></label></div></section>
    <section className="surface full-table-surface"><div className="section-heading"><div><p className="eyebrow">OPERASYON LİSTESİ</p><h2>{filteredOrders.length} iş emri</h2></div></div>
      {isLoading ? <State icon={<RefreshCw className="spin-icon" size={30} />} title="İş emirleri yükleniyor" /> : loadError ? <div className="work-orders-state error"><AlertCircle size={32} /><strong>İş emirleri alınamadı</strong><span>{loadError}</span><button className="secondary-button" onClick={onReload}><RefreshCw size={15} /> Tekrar Dene</button></div> : <div className="table-wrap"><table><thead><tr><th>İş emri</th><th>Müşteri / Şube</th><th>Hizmet</th><th>Saha personeli</th><th>Durum</th><th></th></tr></thead><tbody>
        {filteredOrders.map((order) => <tr key={order.recordId}><td><strong>{order.id}</strong><span>{order.date} · {order.time}</span></td><td><strong>{order.client}</strong><span>{order.branch}</span><a className="table-address table-map-link" href={order.branchMapUrl || `https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(order.branchAddress)}`} target="_blank" rel="noreferrer"><MapPinned size={12} />{order.branchAddress}<ExternalLink size={11} /></a></td><td><strong>{order.service}</strong><span className="work-kind-label">{visitLabel(order.visitType)} · {recurrenceLabel(order.recurrenceType)}</span></td><td><div className="person-cell"><div className="avatar avatar-small avatar-green">{getInitials(order.technician)}</div>{order.technician}</div></td><td><StatusBadge value={order.status} /></td><td><div className="row-action-group"><button className="row-action" aria-label="Detay" onClick={() => onView(order)}><Eye size={17} /></button>{order.technicalStatus !== 'Completed' && order.technicalStatus !== 'InProgress' && <button className="row-action" aria-label="Düzenle" onClick={() => onEdit(order)}><Pencil size={16} /></button>}</div></td></tr>)}
        {filteredOrders.length === 0 && <tr><td colSpan={6} className="work-orders-empty"><Store size={28} /><strong>{customers.length === 0 ? 'Önce müşteri ve şubelerini tanımlayın' : 'Eşleşen iş emri bulunamadı'}</strong><span>Yeni bir plan oluşturabilir veya filtreleri değiştirebilirsiniz.</span><button className="secondary-button" onClick={customers.length === 0 ? onManageCustomers : onCreate}><Plus size={16} /> {customers.length === 0 ? 'Müşteri & Şube Ekle' : 'Yeni İş Emri'}</button></td></tr>}
      </tbody></table></div>}
    </section>
  </section>;
}

function State({ icon, title }: { icon: React.ReactNode; title: string }) { return <div className="work-orders-state">{icon}<strong>{title}</strong></div>; }
function visitLabel(value: string) { return ({ Routine: 'Rutin', Extra: 'Ekstra', EmergencyPaid: 'Ücretli acil', EmergencyFree: 'Ücretsiz acil' } as Record<string, string>)[value] ?? value; }
function recurrenceLabel(value: string) { return ({ Once: 'Tek sefer', Weekly: 'Haftalık', Monthly: 'Aylık', Manual: 'Manuel' } as Record<string, string>)[value] ?? value; }
function getInitials(name: string) { if (name === 'Atama bekliyor') return '?'; return name.split(' ').filter(Boolean).slice(0, 2).map((part) => part[0]?.toLocaleUpperCase('tr-TR')).join(''); }
