namespace Pesneer.Api.Commercial;

public sealed record ProposalLineRequest(string Description, decimal Quantity, string Unit, decimal UnitPrice);
public sealed record CreateProposalRequest(Guid CustomerId, Guid? BranchId, string Title, DateOnly IssueDate, DateOnly ValidUntil, decimal VatRate, decimal DiscountAmount, string? Notes, string? Terms, IReadOnlyList<ProposalLineRequest> Lines);
public sealed record ProposalLineResponse(Guid Id, string Description, decimal Quantity, string Unit, decimal UnitPrice, decimal LineTotal);
public sealed record ProposalResponse(Guid Id, string Number, Guid CustomerId, string CustomerName, Guid? BranchId, string BranchName, string Title, string Status, DateOnly IssueDate, DateOnly ValidUntil, string Currency, decimal Subtotal, decimal DiscountAmount, decimal VatRate, decimal VatAmount, decimal TotalAmount, string? Notes, string? Terms, DateTimeOffset? CustomerDecisionAt, string? CustomerDecisionNote, DateTimeOffset CreatedAt, IReadOnlyList<ProposalLineResponse> Lines);
public sealed record ContractServicePlanRequest(Guid? BranchId, Guid? EmployeeAccountId, string ServiceType, string RecurrenceType, int VisitsPerPeriod, int PreferredDay, string PreferredTime, int DurationMinutes, decimal BranchPrice);
public sealed record ConvertProposalRequest(DateOnly StartDate, DateOnly EndDate, string BillingFrequency, int BillingDay, int PaymentTermDays, decimal? PeriodAmount, string? Scope, string? Terms, bool AutoRenew = false, int RenewalNoticeDays = 60, decimal AnnualPriceIncreaseRate = 0, int FreeEmergencyCallsPerYear = 0, decimal ExtraEmergencyCallPrice = 0, int ResponseTimeHours = 24, IReadOnlyList<ContractServicePlanRequest>? ServicePlans = null);
public sealed record ContractServicePlanResponse(Guid Id, Guid? BranchId, string BranchName, Guid? EmployeeAccountId, string EmployeeName, string ServiceType, string RecurrenceType, int VisitsPerPeriod, int PreferredDay, string PreferredTime, int DurationMinutes, decimal BranchPrice, DateOnly? GeneratedThrough, bool IsActive, int GeneratedWorkOrderCount);
public sealed record ContractResponse(Guid Id, string Number, Guid CustomerId, string CustomerName, Guid? BranchId, string BranchName, Guid? ProposalId, string Title, string Status, DateOnly StartDate, DateOnly EndDate, string BillingFrequency, int BillingDay, int PaymentTermDays, decimal PeriodAmount, string Currency, string? Scope, string? Terms, bool AutoRenew, int RenewalNoticeDays, decimal AnnualPriceIncreaseRate, int FreeEmergencyCallsPerYear, decimal ExtraEmergencyCallPrice, int ResponseTimeHours, int DaysUntilEnd, bool RenewalDue, int InvoiceCount, decimal RemainingBalance, int GeneratedWorkOrderCount, DateTimeOffset CreatedAt, IReadOnlyList<ContractServicePlanResponse> ServicePlans);
public sealed record GenerateContractWorkOrdersRequest(DateOnly? ThroughDate);
public sealed record ContractGenerationResponse(Guid ContractId, DateOnly GeneratedThrough, int CreatedCount, int SkippedExistingCount);
public sealed record ReceivableResponse(Guid Id, string Number, Guid CustomerId, string CustomerName, Guid? BranchId, string BranchName, Guid? ContractId, string ContractNumber, string Description, DateOnly IssueDate, DateOnly DueDate, decimal Amount, decimal PaidAmount, decimal Balance, string Currency, string Status, DateTimeOffset? PaidAt, string? PaymentNote);
public sealed record RecordPaymentRequest(decimal Amount, string? Note);
public sealed record WorkOrderEconomicsRequest(decimal Revenue, decimal PersonnelHourlyCost, decimal DistanceKm, decimal FuelCost, decimal RepeatVisitCost, decimal EmergencyCallCost, decimal OtherCost);
public sealed record ProfitabilityRowResponse(Guid CustomerId, string CustomerName, Guid? BranchId, string BranchName, decimal Revenue, decimal ProductCost, decimal PersonnelCost, decimal FuelCost, decimal RepeatVisitCost, decimal EmergencyCallCost, decimal OtherCost, decimal GrossProfit, decimal MarginPercent, decimal ReceivableBalance, int CompletedVisits, int RepeatVisits, int EmergencyCalls, int RenewalScore);
public sealed record ProfitabilitySummaryResponse(decimal Revenue, decimal TotalCost, decimal GrossProfit, decimal MarginPercent, decimal ReceivableBalance, decimal CollectionRate, int ContractsExpiringIn90Days, IReadOnlyList<ProfitabilityRowResponse> Rows);
