namespace Pesneer.Api.Commercial;

public sealed record ProposalLineRequest(string Description, decimal Quantity, string Unit, decimal UnitPrice);
public sealed record CreateProposalRequest(Guid CustomerId, Guid? BranchId, string Title, DateOnly IssueDate, DateOnly ValidUntil, decimal VatRate, decimal DiscountAmount, string? Notes, string? Terms, IReadOnlyList<ProposalLineRequest> Lines);
public sealed record ProposalLineResponse(Guid Id, string Description, decimal Quantity, string Unit, decimal UnitPrice, decimal LineTotal);
public sealed record ProposalResponse(Guid Id, string Number, Guid CustomerId, string CustomerName, Guid? BranchId, string BranchName, string Title, string Status, DateOnly IssueDate, DateOnly ValidUntil, string Currency, decimal Subtotal, decimal DiscountAmount, decimal VatRate, decimal VatAmount, decimal TotalAmount, string? Notes, string? Terms, DateTimeOffset CreatedAt, IReadOnlyList<ProposalLineResponse> Lines);
public sealed record ConvertProposalRequest(DateOnly StartDate, DateOnly EndDate, string BillingFrequency, int BillingDay, int PaymentTermDays, decimal? PeriodAmount, string? Scope, string? Terms);
public sealed record ContractResponse(Guid Id, string Number, Guid CustomerId, string CustomerName, Guid? BranchId, string BranchName, Guid? ProposalId, string Title, string Status, DateOnly StartDate, DateOnly EndDate, string BillingFrequency, int BillingDay, int PaymentTermDays, decimal PeriodAmount, string Currency, string? Scope, string? Terms, int InvoiceCount, decimal RemainingBalance, DateTimeOffset CreatedAt);
public sealed record ReceivableResponse(Guid Id, string Number, Guid CustomerId, string CustomerName, Guid? BranchId, string BranchName, Guid? ContractId, string ContractNumber, string Description, DateOnly IssueDate, DateOnly DueDate, decimal Amount, decimal PaidAmount, decimal Balance, string Currency, string Status, DateTimeOffset? PaidAt, string? PaymentNote);
public sealed record RecordPaymentRequest(decimal Amount, string? Note);
public sealed record WorkOrderEconomicsRequest(decimal Revenue, decimal PersonnelHourlyCost, decimal DistanceKm, decimal FuelCost, decimal RepeatVisitCost, decimal EmergencyCallCost, decimal OtherCost);
public sealed record ProfitabilityRowResponse(Guid CustomerId, string CustomerName, Guid? BranchId, string BranchName, decimal Revenue, decimal ProductCost, decimal PersonnelCost, decimal FuelCost, decimal RepeatVisitCost, decimal EmergencyCallCost, decimal OtherCost, decimal GrossProfit, decimal MarginPercent, decimal ReceivableBalance, int CompletedVisits, int RepeatVisits, int EmergencyCalls, int RenewalScore);
public sealed record ProfitabilitySummaryResponse(decimal Revenue, decimal TotalCost, decimal GrossProfit, decimal MarginPercent, decimal ReceivableBalance, decimal CollectionRate, int ContractsExpiringIn90Days, IReadOnlyList<ProfitabilityRowResponse> Rows);
