namespace Pesneer.Api.Customers;

public sealed record CustomerPortalBranchResponse(Guid Id, string Name, string Code, string Address, string? City, string? District, string? PhoneNumber, string? Email, string? MapUrl);
public sealed record CustomerPortalWorkOrderResponse(Guid Id, string Number, Guid? BranchId, string BranchName, string ServiceType, string VisitType, DateTimeOffset ScheduledAt, int DurationMinutes, string Status, string EmployeeName, string? CompletionNote, string? Recommendation);
public sealed record EmergencyHistoryResponse(string Status, string? Note, DateTimeOffset OccurredAt, string ChangedBy);
public sealed record EmergencyRequestResponse(Guid Id, string Number, Guid CustomerId, string CustomerName, Guid? BranchId, string BranchName, string RequestType, string Subject, string ServiceType, Guid? ContractId, string ContractCoverage, decimal ChargeAmount, DateTimeOffset? SlaDueAt, string Priority, string Status, string Description, string? ContactPhone, Guid? AssignedEmployeeAccountId, string EmployeeName, DateTimeOffset RequestedAt, DateTimeOffset? DueAt, DateTimeOffset? RequestedAppointmentAt, string ClosureApprovalStatus, DateTimeOffset? ClosureApprovedAt, string? ClosureApprovalNote, DateTimeOffset? AcknowledgedAt, DateTimeOffset? CompletedAt, IReadOnlyList<EmergencyHistoryResponse> History);
public sealed record CustomerPortalSummaryResponse(Guid CustomerId, string CustomerName, string Scope, IReadOnlyList<CustomerPortalBranchResponse> Branches, IReadOnlyList<CustomerPortalWorkOrderResponse> UpcomingWorkOrders, IReadOnlyList<CustomerPortalWorkOrderResponse> CompletedWorkOrders, IReadOnlyList<EmergencyRequestResponse> EmergencyRequests);
public sealed record CustomerProposalLineResponse(Guid Id, string Description, decimal Quantity, string Unit, decimal UnitPrice, decimal LineTotal);
public sealed record CustomerProposalResponse(Guid Id, string Number, Guid? BranchId, string BranchName, string Title, string Status, DateOnly IssueDate, DateOnly ValidUntil, string Currency, decimal Subtotal, decimal DiscountAmount, decimal VatRate, decimal VatAmount, decimal TotalAmount, string? Notes, string? Terms, DateTimeOffset? DecisionAt, string? DecisionNote, bool CanDecide, IReadOnlyList<CustomerProposalLineResponse> Lines);
public sealed record CustomerContractServicePlanResponse(Guid Id, Guid? BranchId, string BranchName, string ServiceType, string RecurrenceType, int VisitsPerPeriod, int PreferredDay, string PreferredTime, int DurationMinutes, DateOnly? GeneratedThrough);
public sealed record CustomerContractResponse(Guid Id, string Number, Guid? BranchId, string BranchName, string Title, string Status, DateOnly StartDate, DateOnly EndDate, string BillingFrequency, int PaymentTermDays, decimal PeriodAmount, string Currency, string? Scope, string? Terms, int InstallmentCount, decimal RemainingBalance, bool AutoRenew, int RenewalNoticeDays, decimal AnnualPriceIncreaseRate, int FreeEmergencyCallsPerYear, decimal ExtraEmergencyCallPrice, int ResponseTimeHours, int GeneratedWorkOrderCount, IReadOnlyList<CustomerContractServicePlanResponse> ServicePlans);
public sealed record CustomerReceivableResponse(Guid Id, string Number, Guid? BranchId, string BranchName, string ContractNumber, string Description, DateOnly IssueDate, DateOnly DueDate, decimal Amount, decimal PaidAmount, decimal Balance, string Currency, string Status, DateTimeOffset? PaidAt);
public sealed record CustomerCommercialSummaryResponse(decimal OpenBalance, int OverdueCount, int PendingProposalCount, IReadOnlyList<CustomerProposalResponse> Proposals, IReadOnlyList<CustomerContractResponse> Contracts, IReadOnlyList<CustomerReceivableResponse> Receivables);
public sealed record CustomerProposalDecisionRequest(bool Accepted, string? Note);
public sealed record CreateEmergencyRequestRequest(Guid? BranchId, string? RequestType, string? Subject, string? ServiceType, string Priority, string Description, string? ContactPhone, DateTimeOffset? DueAt, DateTimeOffset? RequestedAppointmentAt);
public sealed record UpdateEmergencyRequestRequest(string Status, Guid? EmployeeAccountId, string? Note, DateTimeOffset? DueAt);
public sealed record RequestMessageRequest(string Message);
public sealed record ClosureApprovalRequest(bool Approved, string? Note);
