import { useEffect, useMemo, useState, type FormEvent } from 'react';
import { BarChart3, BrainCircuit, Download, Eye, FileArchive, FileSpreadsheet, FileText, FolderArchive, MapPin, Plus, RefreshCw, ShieldAlert, Upload, X } from 'lucide-react';
import {
  createRiskAnalysis, createTrendAnalysis, downloadQualityDocument, getQualityAnalyses, getQualityDocuments, getQualityLocations,
  QualitySessionExpiredError, uploadQualityDocument, type CreateRiskAnalysisInput, type CreateTrendAnalysisInput,
  type QualityAnalysis, type QualityDocument, type QualityLocation, type RiskAnswer,
} from '../../services/qualityApi';

type CenterTab = 'trend' | 'risk' | 'documents';
type Props = { accessToken: string; mode: 'staff' | 'customer'; onSessionExpired: () => void; standalone?: boolean; initialTab?: CenterTab };

export default function QualityCenter({ accessToken, mode, onSessionExpired, standalone = false, initialTab = 'trend' }: Props) {
  const [tab, setTab] = useState<CenterTab>(initialTab); const [locations, setLocations] = useState<QualityLocation[]>([]);
  const [analyses, setAnalyses] = useState<QualityAnalysis[]>([]); const [documents, setDocuments] = useState<QualityDocument[]>([]);
  const [loading, setLoading] = useState(true); const [error, setError] = useState<string | null>(null);
  const [trendOpen, setTrendOpen] = useState(false); const [riskOpen, setRiskOpen] = useState(false); const [uploadOpen, setUploadOpen] = useState(false);
  const [category, setCategory] = useState('');

  const load = async () => {
    setLoading(true); setError(null);
    try {
      const [analysisItems, documentItems, locationItems] = await Promise.all([
        getQualityAnalyses(accessToken), getQualityDocuments(accessToken), mode === 'staff' ? getQualityLocations(accessToken) : Promise.resolve([]),
      ]);
      setAnalyses(analysisItems); setDocuments(documentItems); setLocations(locationItems);
    } catch (loadError) {
      if (loadError instanceof QualitySessionExpiredError) return onSessionExpired();
      setError(loadError instanceof Error ? loadError.message : 'Analiz ve belgeler yüklenemedi.');
    } finally { setLoading(false); }
  };
  useEffect(() => { void load(); }, [accessToken]);

  const trends = analyses.filter((item) => item.analysisType === 'Trend'); const risks = analyses.filter((item) => item.analysisType === 'Risk');
  const filteredDocuments = category ? documents.filter((item) => item.category === category) : documents;
  const handleTrend = async (input: CreateTrendAnalysisInput) => { const created = await createTrendAnalysis(accessToken, input); setAnalyses((current) => [created, ...current]); await refreshDocuments(accessToken, setDocuments); setTrendOpen(false); };
  const handleRisk = async (input: CreateRiskAnalysisInput) => { const created = await createRiskAnalysis(accessToken, input); setAnalyses((current) => [created, ...current]); await refreshDocuments(accessToken, setDocuments); setRiskOpen(false); };
  const handleUpload = async (input: Parameters<typeof uploadQualityDocument>[1]) => { const created = await uploadQualityDocument(accessToken, input); setDocuments((current) => [created, ...current]); setUploadOpen(false); };
  const download = async (document: QualityDocument, open = false) => { try { await downloadQualityDocument(accessToken, document, open); } catch (downloadError) { if (downloadError instanceof QualitySessionExpiredError) return onSessionExpired(); setError(downloadError instanceof Error ? downloadError.message : 'Belge indirilemedi.'); } };
  const documentByAnalysis = useMemo(() => new Map(documents.filter((item) => item.analysisId).map((item) => [item.analysisId!, item])), [documents]);

  return <section className={`quality-center ${standalone ? 'page quality-center-page' : 'quality-center-embedded'}`}>
    {standalone && <div className="page-heading"><div><p className="eyebrow">KALİTE, UYUM & İZLENEBİLİRLİK</p><h1>Belgeler & Analizler</h1><p>Trendleri, konuma bağlı riskleri ve kurumsal belgeleri düzenli bir arşivde yönetin.</p></div><button className="secondary-button" onClick={() => void load()}><RefreshCw size={16} /> Yenile</button></div>}
    <nav className="quality-tabs"><button className={tab === 'trend' ? 'active' : ''} onClick={() => setTab('trend')}><BarChart3 size={18} /><span>Trend Analizleri</span><b>{trends.length}</b></button><button className={tab === 'risk' ? 'active' : ''} onClick={() => setTab('risk')}><BrainCircuit size={18} /><span>Risk Analizleri</span><b>{risks.length}</b></button><button className={tab === 'documents' ? 'active' : ''} onClick={() => setTab('documents')}><FolderArchive size={18} /><span>Belge Arşivi</span><b>{documents.length}</b></button></nav>
    {error && <div className="quality-error"><ShieldAlert size={17} />{error}<button onClick={() => setError(null)}>Kapat</button></div>}
    {loading ? <div className="surface quality-loading"><RefreshCw className="spin-icon" /><strong>Kalite kayıtları hazırlanıyor…</strong></div> : <>
      {tab === 'trend' && <AnalysisList type="Trend" items={trends} staff={mode === 'staff'} onCreate={() => setTrendOpen(true)} documents={documentByAnalysis} onDownload={download} />}
      {tab === 'risk' && <AnalysisList type="Risk" items={risks} staff={mode === 'staff'} onCreate={() => setRiskOpen(true)} documents={documentByAnalysis} onDownload={download} />}
      {tab === 'documents' && <DocumentLibrary items={filteredDocuments} category={category} onCategory={setCategory} staff={mode === 'staff'} onUpload={() => setUploadOpen(true)} onDownload={download} />}
    </>}
    {trendOpen && <TrendAnalysisModal locations={locations} onClose={() => setTrendOpen(false)} onSubmit={handleTrend} />}
    {riskOpen && <RiskAnalysisModal locations={locations} onClose={() => setRiskOpen(false)} onSubmit={handleRisk} />}
    {uploadOpen && <DocumentUploadModal locations={locations} onClose={() => setUploadOpen(false)} onSubmit={handleUpload} />}
  </section>;
}

function AnalysisList({ type, items, staff, onCreate, documents, onDownload }: { type: 'Trend' | 'Risk'; items: QualityAnalysis[]; staff: boolean; onCreate: () => void; documents: Map<string, QualityDocument>; onDownload: (document: QualityDocument, open?: boolean) => void }) {
  const trend = type === 'Trend';
  return <div className="quality-module"><div className="quality-module-heading"><div><p className="eyebrow">{trend ? 'SAHA VERİSİNDEN OTOMATİK' : 'KONUM + SAHA DEĞERLENDİRMESİ'}</p><h2>{trend ? 'Canlı yakalama ve aktivite trendleri' : 'AI destekli risk değerlendirmeleri'}</h2><p>{trend ? 'Personelin saha raporlarına girdiği istasyon, aktivite ve zararlı gözlemleri seçilen dönemde karşılaştırılır.' : 'Yapısal kontrol formu, lokasyon ve güncel hava verisi birlikte değerlendirilerek açıklanabilir öneriler üretilir.'}</p></div>{staff && <button className="primary-button" onClick={onCreate}><Plus size={17} /> {trend ? 'Trend Analizi Oluştur' : 'Risk Analizi Oluştur'}</button>}</div>
    {items.length === 0 ? <div className="surface quality-empty">{trend ? <BarChart3 /> : <BrainCircuit />}<strong>Henüz {trend ? 'trend' : 'risk'} analizi oluşturulmadı</strong><span>{staff ? 'Dijital formu doldurduğunuzda kayıt müşteriye ve belge arşivine otomatik düşer.' : 'Yayınlanan analizler burada görüntülenir.'}</span></div> : <div className="quality-analysis-grid">{items.map((item) => { const document = documents.get(item.id); return <article className="surface quality-analysis-card" key={item.id}><div className="quality-card-top"><span className={`quality-kind ${trend ? 'trend' : 'risk'}`}>{trend ? <BarChart3 /> : <ShieldAlert />}</span><div><small>{item.number}</small><strong>{item.title}</strong><p>{item.customerName} · {item.branchName}</p></div><span className={`quality-score quality-${riskTone(item)}`}><b>{item.score ?? '—'}</b><small>{trend ? item.payload.trendDirection ?? 'Aktivite' : riskLabel(item.level)}</small></span></div><div className="quality-card-metrics">{trend ? <><Metric label="Rapor" value={item.payload.reportCount ?? 0} /><Metric label="İstasyon" value={item.payload.totalStations ?? 0} /><Metric label="Aktif" value={item.payload.activeStations ?? 0} /><Metric label="Yakalama" value={item.payload.totalCaught ?? 0} /></> : <><Metric label="Yapısal" value={`${item.payload.structuralRiskScore ?? 0}/100`} /><Metric label="Hava" value={`${item.payload.weatherRiskScore ?? 0}/100`} /><Metric label="Kontrol" value={item.payload.answers?.length ?? 0} /><Metric label="Seviye" value={riskLabel(item.level)} /></>}</div><p className="quality-summary">{item.summary}</p><div className="quality-card-footer"><span>{formatDateRange(item.periodStart, item.periodEnd)} · {item.createdBy}</span>{document && <div><button onClick={() => onDownload(document, true)}><Eye size={15} /> Görüntüle</button><button onClick={() => onDownload(document)}><Download size={15} /> İndir</button></div>}</div></article>; })}</div>}
  </div>;
}

function DocumentLibrary({ items, category, onCategory, staff, onUpload, onDownload }: { items: QualityDocument[]; category: string; onCategory: (value: string) => void; staff: boolean; onUpload: () => void; onDownload: (document: QualityDocument, open?: boolean) => void }) {
  return <div className="quality-module"><div className="quality-module-heading"><div><p className="eyebrow">KATEGORİK DİJİTAL ARŞİV</p><h2>Belgeler</h2><p>Oluşturulan analizler ve yüklenen PDF, Word, Excel, metin veya görsel dosyaları tek yerde saklanır.</p></div>{staff && <button className="primary-button" onClick={onUpload}><Upload size={17} /> Belge Yükle</button>}</div><div className="surface document-library"><div className="document-filter-row"><label>Kategori<select value={category} onChange={(event) => onCategory(event.target.value)}><option value="">Tüm belgeler</option>{documentCategories.map((item) => <option value={item.value} key={item.value}>{item.label}</option>)}</select></label><span>{items.length} belge</span></div>{items.length === 0 ? <div className="quality-empty"><FileArchive /><strong>Bu kategoride belge yok</strong><span>Yeni analizler ve yüklenen dosyalar burada sıralanır.</span></div> : <div className="document-table"><div className="document-table-head"><span>Belge</span><span>Kategori</span><span>Müşteri / Şube</span><span>Oluşturan</span><span>Tarih</span><span /></div>{items.map((item) => <article key={item.id}><span className="document-name"><i>{documentIcon(item)}</i><span><strong>{item.title}</strong><small>{item.fileName}{item.sizeBytes ? ` · ${formatSize(item.sizeBytes)}` : ' · Dijital form'}</small></span></span><span className="document-category">{categoryLabel(item.category)}</span><span>{item.customerName}<small>{item.branchName}</small></span><span>{item.createdBy}</span><span>{formatDate(item.createdAt)}</span><span className="document-actions">{item.analysisId && <button title="Görüntüle" onClick={() => onDownload(item, true)}><Eye size={16} /></button>}<button title="İndir" onClick={() => onDownload(item)}><Download size={16} /></button></span></article>)}</div>}</div></div>;
}

function TrendAnalysisModal({ locations, onClose, onSubmit }: { locations: QualityLocation[]; onClose: () => void; onSubmit: (input: CreateTrendAnalysisInput) => Promise<void> }) {
  const [locationKey, setLocationKey] = useState(locationValue(locations[0])); const [periodEnd, setPeriodEnd] = useState(dateKey(new Date())); const [periodStart, setPeriodStart] = useState(monthStart(3)); const [saving, setSaving] = useState(false); const [error, setError] = useState<string | null>(null);
  const setMonths = (months: number) => setPeriodStart(monthStart(months, new Date(`${periodEnd}T12:00:00`)));
  const submit = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const location = findLocation(locations, locationKey); if (!location) return setError('Müşteri veya şube seçin.'); const data = new FormData(event.currentTarget); setSaving(true); setError(null); try { await onSubmit({ customerId: location.customerId, branchId: location.branchId, periodStart, periodEnd, title: optional(data, 'title'), findings: optional(data, 'findings'), recommendations: optional(data, 'recommendations') }); } catch (submitError) { setError(messageOf(submitError)); } finally { setSaving(false); } };
  return <div className="modal-layer"><div className="modal quality-form-modal"><ModalTitle icon={<BarChart3 />} eyebrow="TREND ANALİZİ" title="Canlı yakalama & aktivite trendi" description="Onaylı saha raporlarındaki istasyon hareketleri seçilen tarih aralığında otomatik karşılaştırılır." onClose={onClose} /><form onSubmit={submit}><div className="quality-form-note"><FileSpreadsheet /><div><strong>Otomatik veri kaynağı</strong><span>Toplam istasyon, aktivite görülen istasyon, plaka değişimi, yakalama sayısı ve zararlı türleri saha formlarından alınır.</span></div></div><div className="form-grid"><LocationSelect locations={locations} value={locationKey} onChange={setLocationKey} /><label>Analiz başlığı<input name="title" placeholder="Örn. 1. Çeyrek Canlı Yakalama Trend Analizi" /></label><label>Başlangıç<input type="date" value={periodStart} onChange={(event) => setPeriodStart(event.target.value)} required /></label><label>Bitiş<input type="date" value={periodEnd} onChange={(event) => setPeriodEnd(event.target.value)} required /></label><div className="form-field-wide period-presets"><span>Hızlı dönem</span><button type="button" onClick={() => setMonths(1)}>1 aylık</button><button type="button" onClick={() => setMonths(2)}>2 aylık</button><button type="button" onClick={() => setMonths(3)}>3 aylık</button></div><label className="form-field-wide">Saha bulguları<textarea name="findings" rows={3} placeholder="Dönemi etkileyen operasyonel değişiklikler, tadilat, mevsimsel koşullar…" /></label><label className="form-field-wide">Sonuç ve öneriler<textarea name="recommendations" rows={3} placeholder="İstasyon yerleşimi, takip sıklığı veya düzeltici faaliyet önerileri…" /></label></div>{error && <div className="modal-form-error">{error}</div>}<ModalActions saving={saving} onClose={onClose} label="Trend Analizini Yayınla" /></form></div></div>;
}

function RiskAnalysisModal({ locations, onClose, onSubmit }: { locations: QualityLocation[]; onClose: () => void; onSubmit: (input: CreateRiskAnalysisInput) => Promise<void> }) {
  const [locationKey, setLocationKey] = useState(locationValue(locations[0])); const [scores, setScores] = useState<Record<string, number>>(Object.fromEntries(riskQuestions.map((item) => [item.code, 0]))); const [notes, setNotes] = useState<Record<string, string>>({}); const [saving, setSaving] = useState(false); const [error, setError] = useState<string | null>(null);
  const estimated = Math.round(Object.values(scores).reduce((sum, value) => sum + value, 0) / (riskQuestions.length * 4) * 100);
  const submit = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const location = findLocation(locations, locationKey); if (!location) return setError('Müşteri veya şube seçin.'); const data = new FormData(event.currentTarget); const answers: RiskAnswer[] = riskQuestions.map((item) => ({ ...item, score: scores[item.code], note: notes[item.code] || undefined })); setSaving(true); setError(null); try { await onSubmit({ customerId: location.customerId, branchId: location.branchId, assessmentDate: String(data.get('assessmentDate')), title: optional(data, 'title'), findings: optional(data, 'findings'), correctiveActions: optional(data, 'correctiveActions'), recommendations: optional(data, 'recommendations'), answers }); } catch (submitError) { setError(messageOf(submitError)); } finally { setSaving(false); } };
  return <div className="modal-layer"><div className="modal quality-form-modal risk-form-modal"><ModalTitle icon={<BrainCircuit />} eyebrow="AI DESTEKLİ RİSK ANALİZİ" title="Haşere yönetimi risk değerlendirmesi" description="Saha kontrol puanları, lokasyon ve hava koşulları birlikte değerlendirilerek açıklanabilir risk ve öneriler oluşturulur." onClose={onClose} /><form onSubmit={submit}><div className="risk-score-guide"><div><strong>{estimated}/100</strong><span>Form ön değerlendirmesi</span></div><p><b>0:</b> Uygun / risk yok <b>1:</b> Düşük <b>2:</b> Orta <b>3:</b> Yüksek <b>4:</b> Kritik uygunsuzluk</p></div><div className="form-grid risk-header-fields"><LocationSelect locations={locations} value={locationKey} onChange={setLocationKey} /><label>Değerlendirme tarihi<input name="assessmentDate" type="date" defaultValue={dateKey(new Date())} required /></label><label className="form-field-wide">Belge başlığı<input name="title" placeholder="Örn. 2026 Yaz Dönemi Haşere Risk Analizi" /></label></div><div className="risk-question-list">{riskCategories.map((category) => <section key={category}><h3>{category}</h3>{riskQuestions.filter((item) => item.category === category).map((item) => <article key={item.code}><span className="risk-question-code">{item.code}</span><div><strong>{item.question}</strong><small>{item.recommendation}</small><input value={notes[item.code] ?? ''} onChange={(event) => setNotes((current) => ({ ...current, [item.code]: event.target.value }))} placeholder="Saha notu / uygunsuzluk açıklaması" /></div><select value={scores[item.code]} onChange={(event) => setScores((current) => ({ ...current, [item.code]: Number(event.target.value) }))}>{[0,1,2,3,4].map((score) => <option value={score} key={score}>{score}</option>)}</select></article>)}</section>)}</div><div className="form-grid risk-footer-fields"><label className="form-field-wide">Genel bulgular<textarea name="findings" rows={3} placeholder="Gözlenen zararlı izleri, giriş noktaları ve çevresel koşullar…" /></label><label className="form-field-wide">Düzeltici faaliyetler<textarea name="correctiveActions" rows={3} placeholder="Kapatılacak açıklıklar, temizlik, drenaj, atık veya istasyon aksiyonları…" /></label><label className="form-field-wide">Uzman önerisi<textarea name="recommendations" rows={3} placeholder="Mesul müdür veya saha sorumlusunun ek önerileri…" /></label></div>{error && <div className="modal-form-error">{error}</div>}<ModalActions saving={saving} onClose={onClose} label="Risk Analizini Yayınla" /></form></div></div>;
}

function DocumentUploadModal({ locations, onClose, onSubmit }: { locations: QualityLocation[]; onClose: () => void; onSubmit: (input: Parameters<typeof uploadQualityDocument>[1]) => Promise<void> }) {
  const [locationKey, setLocationKey] = useState(''); const [saving, setSaving] = useState(false); const [error, setError] = useState<string | null>(null);
  const submit = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const data = new FormData(event.currentTarget); const file = data.get('file'); if (!(file instanceof File) || !file.size) return setError('Yüklenecek dosyayı seçin.'); const location = findLocation(locations, locationKey); setSaving(true); setError(null); try { await onSubmit({ file, category: String(data.get('category')), title: optional(data, 'title'), description: optional(data, 'description'), customerId: location?.customerId, branchId: location?.branchId }); } catch (submitError) { setError(messageOf(submitError)); } finally { setSaving(false); } };
  return <div className="modal-layer"><div className="modal document-upload-modal"><ModalTitle icon={<Upload />} eyebrow="BELGE ARŞİVİ" title="Yeni belge yükle" description="PDF, Word, Excel, metin veya görsel dosyalarını müşteri ve şube bazında arşivleyin." onClose={onClose} /><form onSubmit={submit}><div className="form-grid"><label>Kategori<select name="category" defaultValue="Other">{documentCategories.map((item) => <option value={item.value} key={item.value}>{item.label}</option>)}</select></label><label>Müşteri / Şube<select value={locationKey} onChange={(event) => setLocationKey(event.target.value)}><option value="">Firma içi belge</option>{locationOptions(locations)}</select></label><label className="form-field-wide">Belge başlığı<input name="title" placeholder="Dosya adı boş bırakılırsa başlık olarak kullanılır" /></label><label className="form-field-wide quality-file-input"><span>Dosya</span><input name="file" type="file" accept=".pdf,.doc,.docx,.xls,.xlsx,.csv,.txt,.png,.jpg,.jpeg,.webp" required /><small>En fazla 15 MB</small></label><label className="form-field-wide">Açıklama<textarea name="description" rows={3} placeholder="Belgenin kapsamı, geçerlilik dönemi veya ilgili notlar…" /></label></div>{error && <div className="modal-form-error">{error}</div>}<ModalActions saving={saving} onClose={onClose} label="Belgeyi Arşivle" /></form></div></div>;
}

function ModalTitle({ icon, eyebrow, title, description, onClose }: { icon: React.ReactNode; eyebrow: string; title: string; description: string; onClose: () => void }) { return <div className="modal-header"><span className="quality-modal-icon">{icon}</span><div><p className="eyebrow">{eyebrow}</p><h2>{title}</h2><p>{description}</p></div><button className="icon-button" onClick={onClose}><X /></button></div>; }
function ModalActions({ saving, onClose, label }: { saving: boolean; onClose: () => void; label: string }) { return <div className="modal-actions"><button type="button" className="secondary-button" onClick={onClose}>Vazgeç</button><button className="primary-button" disabled={saving}>{saving ? 'Hazırlanıyor…' : label}</button></div>; }
function LocationSelect({ locations, value, onChange }: { locations: QualityLocation[]; value: string; onChange: (value: string) => void }) { return <label>Müşteri / Şube<select value={value} onChange={(event) => onChange(event.target.value)} required><option value="">Seçin</option>{locationOptions(locations)}</select></label>; }
function locationOptions(locations: QualityLocation[]) { return locations.map((item) => <option key={locationValue(item)} value={locationValue(item)}>{item.customerName} · {item.branchName}</option>); }
function locationValue(location?: QualityLocation) { return location ? `${location.customerId}|${location.branchId ?? ''}` : ''; }
function findLocation(locations: QualityLocation[], value: string) { return locations.find((item) => locationValue(item) === value); }
function Metric({ label, value }: { label: string; value: string | number }) { return <div><span>{label}</span><strong>{value}</strong></div>; }
function documentIcon(item: QualityDocument) { return item.contentType.includes('spreadsheet') || item.fileName.endsWith('.xlsx') ? <FileSpreadsheet /> : <FileText />; }
function riskTone(item: QualityAnalysis) { if (item.analysisType === 'Trend') return item.payload.trendDirection === 'Artış' ? 'medium' : 'low'; return item.level?.toLowerCase() ?? 'low'; }
function riskLabel(value?: string) { return value === 'High' ? 'Yüksek' : value === 'Medium' ? 'Orta' : value === 'Low' ? 'Düşük' : value ?? '—'; }
function categoryLabel(value: string) { return documentCategories.find((item) => item.value === value)?.label ?? value; }
function formatSize(value: number) { return value >= 1_048_576 ? `${(value / 1_048_576).toFixed(1)} MB` : `${Math.max(1, Math.round(value / 1024))} KB`; }
function formatDate(value: string) { return new Intl.DateTimeFormat('tr-TR', { day: '2-digit', month: 'short', year: 'numeric' }).format(new Date(value)); }
function formatDateRange(start: string, end: string) { return start === end ? formatDate(`${start}T12:00:00`) : `${formatDate(`${start}T12:00:00`)} – ${formatDate(`${end}T12:00:00`)}`; }
function dateKey(value: Date) { return `${value.getFullYear()}-${String(value.getMonth() + 1).padStart(2, '0')}-${String(value.getDate()).padStart(2, '0')}`; }
function monthStart(months: number, end = new Date()) { const value = new Date(end); value.setDate(1); value.setMonth(value.getMonth() - Math.max(0, months - 1)); return dateKey(value); }
function optional(data: FormData, key: string) { const value = String(data.get(key) ?? '').trim(); return value || undefined; }
function messageOf(error: unknown) { return error instanceof Error ? error.message : 'İşlem tamamlanamadı.'; }
async function refreshDocuments(token: string, setter: (items: QualityDocument[]) => void) { setter(await getQualityDocuments(token)); }

const documentCategories = [
  { value: 'TrendAnalyses', label: 'Trend Analizleri' }, { value: 'RiskAnalyses', label: 'Risk Analizleri' },
  { value: 'ServiceReports', label: 'Saha Hizmet Raporları' }, { value: 'Contracts', label: 'Sözleşmeler' },
  { value: 'Certificates', label: 'İzin & Sertifikalar' }, { value: 'Photos', label: 'Fotoğraflar' },
  { value: 'General', label: 'Genel Belgeler' }, { value: 'Other', label: 'Diğer' },
];
const riskCategories = ['Dış alan & çevre', 'Yapısal giriş engelleme', 'İç alan hijyen & proses', 'İzleme & kayıt sistemi'];
const riskQuestions: Omit<RiskAnswer, 'score' | 'note'>[] = [
  { code: 'D01', category: riskCategories[0], question: 'Çöp ve atık alanları kapalı, temiz ve binadan uygun mesafede mi?', recommendation: 'Atık kaplarını kapalı tutun; sızıntı ve organik kalıntıları günlük giderin.' },
  { code: 'D02', category: riskCategories[0], question: 'Durgun su, bozuk drenaj veya sürekli nemli alan bulunuyor mu?', recommendation: 'Durgun suyu kaldırın; oluk, rögar ve drenaj hatlarını iyileştirin.' },
  { code: 'D03', category: riskCategories[0], question: 'Bitki örtüsü, palet veya malzeme yığınları dış cepheye temas ediyor mu?', recommendation: 'Cephe çevresinde kontrol bandı oluşturun; yığınları zeminden ve duvardan ayırın.' },
  { code: 'D04', category: riskCategories[0], question: 'Komşu işletme, kanal, pazar veya boş arazi kaynaklı dış baskı var mı?', recommendation: 'Sınır hattı izleme istasyonlarını ve kontrol sıklığını artırın.' },
  { code: 'Y01', category: riskCategories[1], question: 'Kapı altı, pencere ve yükleme alanlarında açıklık bulunuyor mu?', recommendation: 'Kapı fırçası, sineklik ve otomatik kapanma sistemlerini tamamlayın.' },
  { code: 'Y02', category: riskCategories[1], question: 'Boru, kablo, duvar ve zemin geçişleri sızdırmaz mı?', recommendation: 'Geçiş açıklıklarını kemirgene dayanıklı malzemeyle kapatın.' },
  { code: 'Y03', category: riskCategories[1], question: 'Giderlerde kapak, sifon ve geri tepme önlemi yeterli mi?', recommendation: 'Gider kapaklarını sabitleyin; kuru sifonları ve çatlak hatları onarın.' },
  { code: 'Y04', category: riskCategories[1], question: 'Çatı, havalandırma ve dış cephe menfezleri korunuyor mu?', recommendation: 'Menfezlere uygun tel kafes uygulayın; çatı boşluklarını kontrol edin.' },
  { code: 'İ01', category: riskCategories[2], question: 'Gıda kırıntısı, döküntü ve yağ kalıntısı vardiya sonunda tamamen temizleniyor mu?', recommendation: 'Kritik üretim alanları için vardiya sonu doğrulama listesi uygulayın.' },
  { code: 'İ02', category: riskCategories[2], question: 'Su kaçağı, yoğuşma veya erişilebilir su kaynağı bulunuyor mu?', recommendation: 'Kaçakları giderin; yoğunlaşma ve temizlik suyu birikimini önleyin.' },
  { code: 'İ03', category: riskCategories[2], question: 'Stoklar duvar ve zeminden ayrı, FIFO/FEFO düzeninde mi?', recommendation: 'Depolama mesafelerini koruyun; ürün rotasyonu ve ambalaj bütünlüğünü doğrulayın.' },
  { code: 'İ04', category: riskCategories[2], question: 'Atık iç alanda bekliyor veya kapaksız taşınıyor mu?', recommendation: 'Atık çıkarma sıklığını artırın; kapalı ve yıkanabilir ekipman kullanın.' },
  { code: 'K01', category: riskCategories[3], question: 'İstasyon planı güncel, numaralı ve saha ile uyumlu mu?', recommendation: 'İstasyon krokisini güncelleyin; her noktayı benzersiz kodla eşleştirin.' },
  { code: 'K02', category: riskCategories[3], question: 'İstasyonlar sağlam, erişilebilir ve hedef zararlı için uygun konumda mı?', recommendation: 'Hasarlı plaka ve istasyonları değiştirin; yerleşimi aktiviteye göre revize edin.' },
  { code: 'K03', category: riskCategories[3], question: 'Aktivite, yakalama ve düzeltici faaliyet kayıtları eksiksiz mi?', recommendation: 'Her kontrolde sayısal aktivite ve kapanış kanıtını dijital kayda bağlayın.' },
  { code: 'K04', category: riskCategories[3], question: 'Canlı zararlı, dışkı, kemirme, yuva veya iz bulgusu var mı?', recommendation: 'Bulguyu fotoğrafla kayıt altına alın; yoğunluğa göre acil kök neden incelemesi başlatın.' },
];
